package com.fitnessapp.nutrition.impl.service;

import com.fitnessapp.nutrition.common.dto.*;
import com.fitnessapp.user.common.dto.UserDto;
import com.fitnessapp.user.sal.UserServiceSalClient;
import com.fitnessapp.nutrition.impl.model.*;
import com.fitnessapp.nutrition.impl.repository.NutritionPlanRepository;
import com.fitnessapp.nutrition.impl.repository.UserNutritionPlanRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.util.*;

@Service @RequiredArgsConstructor @Slf4j
public class AIBasedNutritionService implements AIBasedNutritionOperations {
    private final NutritionPlanRepository planRepo;
    private final UserNutritionPlanRepository userPlanRepo;
    private final GeminiService geminiService;
    private final NutritionService nutritionService;
    private final UserServiceSalClient userServiceSalClient;

    @Transactional
    public NutritionPlanDTO generatePersonalizedPlan(String email, GenerateNutritionPlanRequest request) {
        UserDto user = userServiceSalClient.getUserByEmail(email);
        String dietType = determineDietType(user, request);
        String goal = determineGoal(user, request);
        int targetCalories = request.getTargetCalories() != null ? request.getTargetCalories() : calculateCalories(user, goal);
        String region = request.getRegion() != null ? request.getRegion() : (user.getProfile() != null ? user.getProfile().getRegion() : "NORTH");

        NutritionPlan plan = null;

        // Try AI-based generation first
        if (geminiService.isAvailable()) {
            try {
                Set<Meal> meals = geminiService.generateMeals(user, request, dietType, goal, targetCalories);
                plan = new NutritionPlan();
                plan.setName("AI Personalized: " + goal + " (" + dietType + ")");
                plan.setDescription("Personalized plan generated by AI for " + (user.getProfile() != null ? user.getProfile().getFirstName() : "User"));
                plan.setRegion(region); plan.setDietType(dietType); plan.setGoal(goal);
                plan.setTotalCalories(targetCalories); plan.setDifficulty("MODERATE");
                plan.setDurationDays(30); plan.setIsActive(true); plan.setMeals(meals);

                double totalProtein = 0, totalCarbs = 0, totalFat = 0;
                for (Meal m : meals) {
                    totalProtein += m.getProteinGrams() != null ? m.getProteinGrams() : 0;
                    totalCarbs += m.getCarbsGrams() != null ? m.getCarbsGrams() : 0;
                    totalFat += m.getFatGrams() != null ? m.getFatGrams() : 0;
                }
                plan.setProteinGrams(totalProtein); plan.setCarbsGrams(totalCarbs); plan.setFatGrams(totalFat);
                plan = planRepo.save(plan);
                log.info("AI-generated nutrition plan created for user: {}", email);
            } catch (Exception e) {
                log.warn("AI plan generation failed, falling back to pre-built plans: {}", e.getMessage());
                plan = null;
            }
        } else {
            log.info("AI service not available, using pre-built plans for user: {}", email);
        }

        // Fallback: build a personalized plan from pre-built data using food preferences
        if (plan == null) {
            plan = buildFallbackPlan(request, user, region, dietType, goal, targetCalories);
            log.info("Using fallback plan '{}' for user: {}", plan.getName(), email);
        }

        // Auto-enroll user
        userPlanRepo.deactivateAllActiveForUser(user.getId());
        UserNutritionPlan userPlan = new UserNutritionPlan();
        userPlan.setUserId(user.getId()); userPlan.setNutritionPlan(plan);
        userPlan.setStartDate(LocalDate.now()); userPlan.setEndDate(LocalDate.now().plusDays(plan.getDurationDays() != null ? plan.getDurationDays() : 30));
        userPlan.setStatus("ACTIVE"); userPlan.setCurrentDay(1);
        userPlan.setTotalMeals(plan.getMeals() != null ? plan.getMeals().size() * 30 : 0);
        userPlanRepo.save(userPlan);

        return nutritionService.convertToDTOWithMeals(plan);
    }

    /**
     * Builds a fallback plan from pre-built data, customized with user's food preferences
     * and custom meal timings.
     */
    private NutritionPlan buildFallbackPlan(GenerateNutritionPlanRequest request, UserDto user,
                                            String region, String dietType, String goal, int targetCalories) {
        // Try to find a matching template plan
        NutritionPlan templatePlan = findBestMatchingPlan(region, dietType, goal);
        if (templatePlan != null && templatePlan.getId() != null) {
            templatePlan = planRepo.findByIdWithMealsAndFoodItems(templatePlan.getId()).orElse(templatePlan);
        }

        // Determine which meals user wants
        List<GenerateNutritionPlanRequest.CustomMeal> requestedMeals = request.getCustomMeals();
        boolean hasCustomMeals = requestedMeals != null && !requestedMeals.isEmpty();

        // Create a new personalized plan
        NutritionPlan plan = new NutritionPlan();
        String userName = user.getProfile() != null ? user.getProfile().getFirstName() : "User";
        plan.setName("Personalized " + goal + " Plan (" + dietType + ")");
        plan.setDescription("Customized plan for " + userName + " based on your food preferences");
        plan.setRegion(region); plan.setDietType(dietType); plan.setGoal(goal);
        plan.setTotalCalories(targetCalories); plan.setDifficulty("MODERATE");
        plan.setDurationDays(30); plan.setIsActive(true);

        Set<Meal> meals = new LinkedHashSet<>();
        GenerateNutritionPlanRequest.FoodPreferences foodPrefs = request.getFoodPreferences();

        if (hasCustomMeals) {
            // Build meals based on user's custom meal schedule and food preferences
            int mealCount = (int) requestedMeals.stream().filter(m -> m.getEnabled() == null || m.getEnabled()).count();
            int caloriesPerMeal = mealCount > 0 ? targetCalories / mealCount : targetCalories;

            for (GenerateNutritionPlanRequest.CustomMeal customMeal : requestedMeals) {
                if (customMeal.getEnabled() != null && !customMeal.getEnabled()) continue;

                String mealType = customMeal.getType() != null ? customMeal.getType() : "BREAKFAST";

                // Try to find matching meal from template
                Meal templateMeal = null;
                if (templatePlan != null && templatePlan.getMeals() != null) {
                    templateMeal = templatePlan.getMeals().stream()
                        .filter(m -> mealType.equalsIgnoreCase(m.getMealType()))
                        .findFirst().orElse(null);
                }

                if (templateMeal != null) {
                    // Clone the template meal with custom time, filtering by food preferences
                    Meal meal = cloneMealWithPreferences(templateMeal, customMeal, foodPrefs, region);
                    // If all food items were filtered out, generate from scratch
                    if (meal.getFoodItems() == null || meal.getFoodItems().isEmpty()) {
                        meal = generateMealFromPreferences(customMeal, foodPrefs, dietType, region, caloriesPerMeal);
                    }
                    meals.add(meal);
                } else {
                    // Generate a meal from scratch based on food preferences
                    Meal meal = generateMealFromPreferences(customMeal, foodPrefs, dietType, region, caloriesPerMeal);
                    meals.add(meal);
                }
            }
        } else if (templatePlan != null && templatePlan.getMeals() != null) {
            // Use template meals directly
            int mealCount = templatePlan.getMeals().size();
            int calPerMeal = mealCount > 0 ? targetCalories / mealCount : targetCalories;
            for (Meal templateMeal : templatePlan.getMeals()) {
                Meal meal = cloneMealWithPreferences(templateMeal, null, foodPrefs, region);
                if (meal.getFoodItems() == null || meal.getFoodItems().isEmpty()) {
                    GenerateNutritionPlanRequest.CustomMeal cm = new GenerateNutritionPlanRequest.CustomMeal(
                        null, templateMeal.getName(), templateMeal.getMealType(), templateMeal.getTimeOfDay(), true);
                    meal = generateMealFromPreferences(cm, foodPrefs, dietType, region, calPerMeal);
                }
                meals.add(meal);
            }
        } else {
            // No template found at all, generate basic meals
            meals.add(generateMealFromPreferences(
                new GenerateNutritionPlanRequest.CustomMeal(1, "Breakfast", "BREAKFAST", "8:00 AM", true),
                foodPrefs, dietType, region, targetCalories / 3));
            meals.add(generateMealFromPreferences(
                new GenerateNutritionPlanRequest.CustomMeal(2, "Lunch", "LUNCH", "1:00 PM", true),
                foodPrefs, dietType, region, targetCalories / 3));
            meals.add(generateMealFromPreferences(
                new GenerateNutritionPlanRequest.CustomMeal(3, "Dinner", "DINNER", "8:00 PM", true),
                foodPrefs, dietType, region, targetCalories / 3));
        }

        // Add workout meals if requested
        if (Boolean.TRUE.equals(request.getIncludePreWorkoutMeal())) {
            meals.add(createWorkoutMeal("Pre-Workout Snack", "SNACK",
                request.getPreWorkoutTime() != null ? request.getPreWorkoutTime() : "5:00 PM",
                200, foodPrefs, region));
        }
        if (Boolean.TRUE.equals(request.getIncludePostWorkoutMeal())) {
            meals.add(createWorkoutMeal("Post-Workout Recovery", "SNACK",
                request.getPostWorkoutTime() != null ? request.getPostWorkoutTime() : "7:00 PM",
                300, foodPrefs, region));
        }

        plan.setMeals(meals);

        // Calculate plan-level totals from actual meal data
        int planCalories = 0; double totalProtein = 0, totalCarbs = 0, totalFat = 0;
        for (Meal m : meals) {
            planCalories += m.getCalories() != null ? m.getCalories() : 0;
            totalProtein += m.getProteinGrams() != null ? m.getProteinGrams() : 0;
            totalCarbs += m.getCarbsGrams() != null ? m.getCarbsGrams() : 0;
            totalFat += m.getFatGrams() != null ? m.getFatGrams() : 0;
        }
        plan.setTotalCalories(planCalories);
        plan.setProteinGrams(totalProtein); plan.setCarbsGrams(totalCarbs); plan.setFatGrams(totalFat);

        return planRepo.save(plan);
    }

    /** Clones a template meal, applying custom timing and filtering food items by preferences. */
    private Meal cloneMealWithPreferences(Meal template, GenerateNutritionPlanRequest.CustomMeal customMeal,
                                          GenerateNutritionPlanRequest.FoodPreferences prefs, String region) {
        Meal meal = new Meal();
        meal.setName(customMeal != null ? customMeal.getName() : template.getName());
        meal.setMealType(customMeal != null && customMeal.getType() != null ? customMeal.getType() : template.getMealType());
        meal.setTimeOfDay(customMeal != null && customMeal.getTime() != null ? customMeal.getTime() : template.getTimeOfDay());
        meal.setDayNumber(1);
        meal.setPreparationTips(template.getPreparationTips());

        Set<FoodItem> items = new LinkedHashSet<>();
        if (template.getFoodItems() != null) {
            for (FoodItem fi : template.getFoodItems()) {
                if (isFoodAllowed(fi, prefs)) {
                    FoodItem cloned = cloneFoodItem(fi);
                    items.add(cloned);
                }
            }
        }
        meal.setFoodItems(items);

        // Calculate calories and macros from actual food items
        int totalCal = 0; double protein = 0, carbs = 0, fat = 0;
        for (FoodItem fi : items) {
            totalCal += fi.getCalories() != null ? fi.getCalories() : 0;
            protein += fi.getProteinGrams() != null ? fi.getProteinGrams() : 0;
            carbs += fi.getCarbsGrams() != null ? fi.getCarbsGrams() : 0;
            fat += fi.getFatGrams() != null ? fi.getFatGrams() : 0;
        }
        meal.setCalories(totalCal);
        meal.setProteinGrams(protein); meal.setCarbsGrams(carbs); meal.setFatGrams(fat);

        return meal;
    }

    /** Checks if a food item is compatible with user's preferences */
    private boolean isFoodAllowed(FoodItem item, GenerateNutritionPlanRequest.FoodPreferences prefs) {
        if (prefs == null) return true;
        String name = item.getName() != null ? item.getName().toLowerCase() : "";

        if (Boolean.FALSE.equals(prefs.getIncludeChicken()) && name.contains("chicken")) return false;
        if (Boolean.FALSE.equals(prefs.getIncludeFish()) && (name.contains("fish") || name.contains("mach"))) return false;
        if (Boolean.FALSE.equals(prefs.getIncludeRedMeat()) && (name.contains("mutton") || name.contains("lamb") || name.contains("beef"))) return false;
        if (Boolean.FALSE.equals(prefs.getIncludeRice()) && name.contains("rice")) return false;
        if (Boolean.FALSE.equals(prefs.getIncludeRoti()) && (name.contains("roti") || name.contains("chapati") || name.contains("paratha"))) return false;
        if (Boolean.FALSE.equals(prefs.getIncludeDal()) && (name.contains("dal") || name.contains("lentil"))) return false;
        if (Boolean.FALSE.equals(prefs.getIncludeMilk()) && name.contains("milk")) return false;
        if (Boolean.FALSE.equals(prefs.getIncludePaneer()) && name.contains("paneer")) return false;
        if (Boolean.FALSE.equals(prefs.getIncludeCurd()) && (name.contains("curd") || name.contains("yogurt") || name.contains("raita"))) return false;

        if (prefs.getDislikedFoods() != null) {
            for (String disliked : prefs.getDislikedFoods()) {
                if (name.contains(disliked.toLowerCase())) return false;
            }
        }
        return true;
    }

    private FoodItem cloneFoodItem(FoodItem src) {
        FoodItem fi = new FoodItem();
        fi.setName(src.getName()); fi.setHindiName(src.getHindiName());
        fi.setDescription(src.getDescription()); fi.setQuantity(src.getQuantity());
        fi.setCalories(src.getCalories()); fi.setProteinGrams(src.getProteinGrams());
        fi.setCarbsGrams(src.getCarbsGrams()); fi.setFatGrams(src.getFatGrams());
        fi.setFiberGrams(src.getFiberGrams()); fi.setIsVegetarian(src.getIsVegetarian());
        fi.setRegion(src.getRegion());
        return fi;
    }

    /** Generates a meal from scratch using food preferences for the given meal type */
    private Meal generateMealFromPreferences(GenerateNutritionPlanRequest.CustomMeal customMeal,
                                              GenerateNutritionPlanRequest.FoodPreferences prefs,
                                              String dietType, String region, int targetCalories) {
        Meal meal = new Meal();
        meal.setName(customMeal.getName());
        meal.setMealType(customMeal.getType());
        meal.setTimeOfDay(customMeal.getTime());
        meal.setDayNumber(1);

        Set<FoodItem> items = new LinkedHashSet<>();
        boolean isVeg = "VEGETARIAN".equalsIgnoreCase(dietType) || "VEGAN".equalsIgnoreCase(dietType);
        String mealType = customMeal.getType() != null ? customMeal.getType() : "LUNCH";

        switch (mealType) {
            case "BREAKFAST":
                items.addAll(generateBreakfastItems(prefs, isVeg, region, targetCalories));
                break;
            case "LUNCH":
                items.addAll(generateLunchItems(prefs, isVeg, region, targetCalories));
                break;
            case "DINNER":
                items.addAll(generateDinnerItems(prefs, isVeg, region, targetCalories));
                break;
            default: // SNACK, MORNING_SNACK, AFTERNOON_SNACK, etc.
                items.addAll(generateSnackItems(prefs, isVeg, region, targetCalories));
                break;
        }

        // Set meal calories and macros from actual items
        int totalCal = 0; double protein = 0, carbs = 0, fat = 0;
        for (FoodItem fi : items) {
            totalCal += fi.getCalories() != null ? fi.getCalories() : 0;
            protein += fi.getProteinGrams() != null ? fi.getProteinGrams() : 0;
            carbs += fi.getCarbsGrams() != null ? fi.getCarbsGrams() : 0;
            fat += fi.getFatGrams() != null ? fi.getFatGrams() : 0;
        }
        meal.setCalories(totalCal);
        meal.setProteinGrams(protein); meal.setCarbsGrams(carbs); meal.setFatGrams(fat);
        meal.setFoodItems(items);

        String tips = "BREAKFAST".equals(mealType) ? "Start your day with protein for sustained energy" :
                      "LUNCH".equals(mealType) ? "Balance your plate with protein, carbs, and vegetables" :
                      "DINNER".equals(mealType) ? "Keep dinner lighter, eat at least 2 hours before sleep" :
                      "Choose nutrient-dense options for snacking";
        meal.setPreparationTips(tips);

        return meal;
    }

    private Set<FoodItem> generateBreakfastItems(GenerateNutritionPlanRequest.FoodPreferences prefs,
                                                   boolean isVeg, String region, int targetCal) {
        Set<FoodItem> items = new LinkedHashSet<>();

        // Eggs for breakfast (if allowed)
        if (!isVeg && prefs != null && prefs.getEggsPerDay() != null && prefs.getEggsPerDay() > 0) {
            int eggs = Math.min(prefs.getEggsPerDay(), 4);
            items.add(buildFoodItem("Boiled Eggs", "उबले अंडे", "Protein-rich boiled eggs", eggs + " eggs",
                eggs * 78, eggs * 6.0, eggs * 0.6, eggs * 5.0, false, region));
        } else if (prefs == null || Boolean.TRUE.equals(prefs.getIncludePaneer())) {
            items.add(buildFoodItem("Paneer Paratha", "पनीर पराठा", "Cottage cheese stuffed flatbread", "2 pieces",
                350, 16.0, 35.0, 14.0, true, region));
        } else {
            items.add(buildFoodItem("Moong Dal Chilla", "मूंग दाल चीला", "Lentil pancake with vegetables", "3 pieces",
                250, 14.0, 28.0, 6.0, true, region));
        }

        // Carb source for breakfast
        if (prefs == null || Boolean.TRUE.equals(prefs.getIncludeRoti())) {
            items.add(buildFoodItem("Whole Wheat Toast", "होल व्हीट टोस्ट", "Toasted whole wheat bread", "2 slices",
                160, 5.0, 28.0, 2.0, true, region));
        } else {
            items.add(buildFoodItem("Poha", "पोहा", "Flattened rice with peanuts & vegetables", "1 bowl",
                200, 4.0, 35.0, 5.0, true, region));
        }

        // Beverage
        if (prefs == null || Boolean.TRUE.equals(prefs.getIncludeMilk())) {
            items.add(buildFoodItem("Milk / Tea", "दूध / चाय", "Warm milk or tea with milk", "1 cup",
                80, 4.0, 6.0, 3.0, true, region));
        } else {
            items.add(buildFoodItem("Black Coffee", "ब्लैक कॉफ़ी", "Fresh brewed coffee", "1 cup",
                5, 0.0, 1.0, 0.0, true, region));
        }

        // Fruit
        items.add(buildFoodItem("Seasonal Fruits", "मौसमी फल", "Banana, apple or papaya", "1 serving",
            80, 1.0, 18.0, 0.3, true, region));

        return items;
    }

    private Set<FoodItem> generateLunchItems(GenerateNutritionPlanRequest.FoodPreferences prefs,
                                               boolean isVeg, String region, int targetCal) {
        Set<FoodItem> items = new LinkedHashSet<>();

        // Protein source
        if (!isVeg && (prefs == null || Boolean.TRUE.equals(prefs.getIncludeChicken()))) {
            items.add(buildFoodItem("Chicken Curry", "चिकन करी", "Homestyle chicken curry", "200g",
                300, 30.0, 8.0, 15.0, false, region));
        } else if (!isVeg && (prefs == null || Boolean.TRUE.equals(prefs.getIncludeFish()))) {
            items.add(buildFoodItem("Fish Curry", "मछली करी", "Light fish curry", "200g",
                250, 28.0, 6.0, 10.0, false, region));
        } else if (prefs == null || Boolean.TRUE.equals(prefs.getIncludeDal())) {
            items.add(buildFoodItem("Dal Tadka", "दाल तड़का", "Seasoned yellow lentil curry", "1 bowl",
                200, 12.0, 25.0, 5.0, true, region));
        } else if (prefs == null || Boolean.TRUE.equals(prefs.getIncludePaneer())) {
            items.add(buildFoodItem("Paneer Bhurji", "पनीर भुर्जी", "Scrambled cottage cheese", "150g",
                280, 18.0, 4.0, 20.0, true, region));
        } else {
            items.add(buildFoodItem("Rajma Curry", "राजमा", "Kidney bean curry", "1 bowl",
                200, 12.0, 30.0, 3.0, true, region));
        }

        // Carb source
        if (prefs == null || Boolean.TRUE.equals(prefs.getIncludeRice())) {
            items.add(buildFoodItem("Steamed Rice", "चावल", "Steamed basmati rice", "1 cup",
                200, 4.0, 45.0, 1.0, true, region));
        } else if (prefs == null || Boolean.TRUE.equals(prefs.getIncludeRoti())) {
            items.add(buildFoodItem("Whole Wheat Roti", "रोटी", "Fresh whole wheat flatbread", "3 pieces",
                300, 9.0, 45.0, 9.0, true, region));
        } else {
            items.add(buildFoodItem("Sweet Potato", "शकरकंद", "Baked sweet potato", "200g",
                180, 3.0, 40.0, 0.5, true, region));
        }

        // Vegetable side
        items.add(buildFoodItem("Mixed Vegetable Curry", "सब्ज़ी", "Seasonal mixed vegetables", "1 bowl",
            120, 4.0, 15.0, 4.0, true, region));

        // Curd/Raita
        if (prefs == null || Boolean.TRUE.equals(prefs.getIncludeCurd())) {
            items.add(buildFoodItem("Fresh Curd", "दही", "Plain yogurt", "1 bowl",
                80, 5.0, 8.0, 3.0, true, region));
        }

        // Salad
        items.add(buildFoodItem("Green Salad", "सलाद", "Cucumber, tomato, onion salad", "1 plate",
            40, 2.0, 6.0, 0.5, true, region));

        return items;
    }

    private Set<FoodItem> generateDinnerItems(GenerateNutritionPlanRequest.FoodPreferences prefs,
                                                boolean isVeg, String region, int targetCal) {
        Set<FoodItem> items = new LinkedHashSet<>();

        // Lighter protein for dinner
        if (!isVeg && (prefs == null || Boolean.TRUE.equals(prefs.getIncludeChicken()))) {
            items.add(buildFoodItem("Grilled Chicken Breast", "ग्रिल्ड चिकन", "Lean grilled chicken", "150g",
                250, 30.0, 0.0, 8.0, false, region));
        } else if (!isVeg && (prefs == null || Boolean.TRUE.equals(prefs.getIncludeFish()))) {
            items.add(buildFoodItem("Grilled Fish", "ग्रिल्ड मछली", "Grilled fish fillet", "150g",
                220, 28.0, 2.0, 6.0, false, region));
        } else if (prefs != null && prefs.getEggsPerDay() != null && prefs.getEggsPerDay() > 0) {
            items.add(buildFoodItem("Egg Curry", "अंडा करी", "Boiled egg curry", "2 eggs",
                220, 14.0, 8.0, 14.0, false, region));
        } else if (prefs == null || Boolean.TRUE.equals(prefs.getIncludePaneer())) {
            items.add(buildFoodItem("Palak Paneer", "पालक पनीर", "Cottage cheese in spinach gravy", "1 bowl",
                260, 16.0, 8.0, 18.0, true, region));
        } else {
            items.add(buildFoodItem("Chana Masala", "छोले", "Spiced chickpea curry", "1 bowl",
                220, 12.0, 30.0, 6.0, true, region));
        }

        // Carb source (lighter for dinner)
        if (prefs == null || Boolean.TRUE.equals(prefs.getIncludeRice())) {
            items.add(buildFoodItem("Steamed Rice", "चावल", "Steamed rice", "1 cup",
                200, 4.0, 45.0, 1.0, true, region));
        } else if (prefs == null || Boolean.TRUE.equals(prefs.getIncludeRoti())) {
            items.add(buildFoodItem("Chapati", "चपाती", "Thin whole wheat bread", "2 pieces",
                160, 5.0, 28.0, 3.0, true, region));
        } else {
            items.add(buildFoodItem("Quinoa", "क्विनोआ", "Steamed quinoa", "1 cup",
                180, 6.0, 30.0, 3.0, true, region));
        }

        // Vegetable
        items.add(buildFoodItem("Mixed Vegetable Curry", "सब्ज़ी", "Seasonal mixed vegetables", "1 bowl",
            120, 4.0, 15.0, 4.0, true, region));

        // Curd
        if (prefs == null || Boolean.TRUE.equals(prefs.getIncludeCurd())) {
            items.add(buildFoodItem("Fresh Curd", "दही", "Plain yogurt", "1 bowl",
                80, 5.0, 8.0, 3.0, true, region));
        }

        return items;
    }

    private Set<FoodItem> generateSnackItems(GenerateNutritionPlanRequest.FoodPreferences prefs,
                                               boolean isVeg, String region, int targetCal) {
        Set<FoodItem> items = new LinkedHashSet<>();
        items.add(buildFoodItem("Mixed Dry Fruits", "मेवे", "Almonds, walnuts, cashews", "1 handful",
            150, 5.0, 10.0, 10.0, true, region));
        items.add(buildFoodItem("Seasonal Fruit", "मौसमी फल", "Apple, banana or orange", "1 piece",
            80, 1.0, 18.0, 0.3, true, region));
        if (prefs == null || Boolean.TRUE.equals(prefs.getIncludeCurd())) {
            items.add(buildFoodItem("Greek Yogurt", "ग्रीक योगर्ट", "High protein yogurt", "1 cup",
                100, 10.0, 8.0, 2.0, true, region));
        }
        return items;
    }

    /** Creates a workout-specific meal */
    private Meal createWorkoutMeal(String name, String type, String time, int targetCalories,
                                    GenerateNutritionPlanRequest.FoodPreferences prefs, String region) {
        Meal meal = new Meal();
        meal.setName(name); meal.setMealType(type); meal.setTimeOfDay(time);
        meal.setDayNumber(1);

        Set<FoodItem> items = new LinkedHashSet<>();
        if (name.contains("Pre")) {
            items.add(buildFoodItem("Banana", "केला", "Quick energy fruit", "2 pieces", 100, 2.0, 25.0, 0.5, true, region));
            items.add(buildFoodItem("Mixed Dry Fruits", "मेवे", "Almonds, cashews, raisins", "1 handful", 100, 3.0, 10.0, 7.0, true, region));
            meal.setPreparationTips("Eat 30-45 minutes before workout for energy");
        } else {
            items.add(buildFoodItem("Whey Protein Shake", "प्रोटीन शेक", "Protein shake with water", "1 scoop", 120, 24.0, 3.0, 1.0, true, region));
            items.add(buildFoodItem("Banana", "केला", "Post workout recovery", "1 piece", 50, 1.0, 12.0, 0.0, true, region));
            meal.setPreparationTips("Consume within 30 minutes after workout for recovery");
        }
        meal.setFoodItems(items);

        // Calculate calories and macros from actual items
        int totalCal = 0;
        double protein = items.stream().mapToDouble(f -> f.getProteinGrams() != null ? f.getProteinGrams() : 0).sum();
        double carbs = items.stream().mapToDouble(f -> f.getCarbsGrams() != null ? f.getCarbsGrams() : 0).sum();
        double fat = items.stream().mapToDouble(f -> f.getFatGrams() != null ? f.getFatGrams() : 0).sum();
        for (FoodItem fi : items) totalCal += fi.getCalories() != null ? fi.getCalories() : 0;
        meal.setCalories(totalCal);
        meal.setProteinGrams(protein); meal.setCarbsGrams(carbs); meal.setFatGrams(fat);
        return meal;
    }

    private FoodItem buildFoodItem(String name, String hindiName, String desc, String qty,
                                    int cal, double protein, double carbs, double fat,
                                    boolean isVeg, String region) {
        FoodItem item = new FoodItem();
        item.setName(name); item.setHindiName(hindiName); item.setDescription(desc);
        item.setQuantity(qty); item.setCalories(cal);
        item.setProteinGrams(protein); item.setCarbsGrams(carbs); item.setFatGrams(fat);
        item.setIsVegetarian(isVeg); item.setRegion(region);
        return item;
    }

    /**
     * Finds the best matching pre-built plan from DB. Progressively relaxes filters.
     */
    private NutritionPlan findBestMatchingPlan(String region, String dietType, String goal) {
        List<NutritionPlan> plans = planRepo.findByFilters(region, dietType, goal);
        if (!plans.isEmpty()) return plans.get(0);
        plans = planRepo.findByFilters(region, dietType, null);
        if (!plans.isEmpty()) return plans.get(0);
        plans = planRepo.findByFilters(null, dietType, goal);
        if (!plans.isEmpty()) return plans.get(0);
        plans = planRepo.findByFilters(null, dietType, null);
        if (!plans.isEmpty()) return plans.get(0);
        plans = planRepo.findByIsActiveTrue();
        if (!plans.isEmpty()) return plans.get(0);
        return null; // No template found - will generate from preferences
    }

    private String determineDietType(UserDto user, GenerateNutritionPlanRequest request) {
        // Check food preferences from the request first
        GenerateNutritionPlanRequest.FoodPreferences fp = request.getFoodPreferences();
        if (fp != null) {
            boolean hasNonVeg = Boolean.TRUE.equals(fp.getIncludeChicken()) ||
                                Boolean.TRUE.equals(fp.getIncludeFish()) ||
                                Boolean.TRUE.equals(fp.getIncludeRedMeat());
            if (hasNonVeg) return "NON_VEGETARIAN";
            if (fp.getEggsPerDay() != null && fp.getEggsPerDay() > 0) return "NON_VEGETARIAN";
        }
        // Fall back to user profile
        if (user.getHealthMetrics() != null && user.getHealthMetrics().getDietaryPreferences() != null) {
            for (String p : user.getHealthMetrics().getDietaryPreferences()) {
                if ("VEGAN".equalsIgnoreCase(p)) return "VEGAN";
                if ("VEGETARIAN".equalsIgnoreCase(p)) return "VEGETARIAN";
            }
        }
        return "NON_VEGETARIAN";
    }

    private String determineGoal(UserDto user, GenerateNutritionPlanRequest request) {
        if (request.getPrimaryGoal() != null && !request.getPrimaryGoal().isEmpty()) return request.getPrimaryGoal();
        if (user.getGoals() != null && !user.getGoals().isEmpty()) return user.getGoals().get(0);
        return "MAINTENANCE";
    }

    private int calculateCalories(UserDto user, String goal) {
        int base = 2000;
        if (user.getHealthMetrics() != null && user.getHealthMetrics().getCurrentWeight() != null) {
            base = (int) (user.getHealthMetrics().getCurrentWeight() * 25);
        }
        if ("WEIGHT_LOSS".equalsIgnoreCase(goal)) return (int) (base * 0.8);
        if ("MUSCLE_BUILDING".equalsIgnoreCase(goal)) return (int) (base * 1.2);
        return base;
    }

    @Override
    public Map<String, Object> estimateFoodMacros(String foodDescription) {
        if (geminiService.isAvailable()) {
            Map<String, Object> result = geminiService.estimateFoodMacros(foodDescription);
            if (result != null) {
                result.put("source", "ai");
                return result;
            }
        }
        // Fallback defaults
        Map<String, Object> fallback = new HashMap<>();
        fallback.put("name", foodDescription);
        fallback.put("calories", 400);
        fallback.put("proteinGrams", 15.0);
        fallback.put("carbsGrams", 45.0);
        fallback.put("fatGrams", 12.0);
        fallback.put("source", "default");
        return fallback;
    }
}

