// Gujarati (ગુજરાતી) - Core translations
export default {
  common: { save: 'સાચવો', cancel: 'રદ કરો', delete: 'કાઢી નાખો', edit: 'સંપાદિત કરો', back: '← પાછા', loading: 'લોડ થઈ રહ્યું છે...', error: 'ભૂલ', success: 'સફળ', confirm: 'ખાતરી કરો', yes: 'હા', no: 'ના', ok: 'બરાબર', retry: 'ફરી પ્રયાસ કરો', done: 'થઈ ગયું', next: 'આગળ', previous: 'પાછળ', submit: 'સબમિટ કરો', search: 'શોધો', noData: 'કોઈ ડેટા ઉપલબ્ધ નથી', comingSoon: 'ટૂંક સમયમાં આવશે' },
  auth: { login: 'લૉગિન', register: 'નોંધણી', email: 'ઇમેઇલ', password: 'પાસવર્ડ', confirmPassword: 'પાસવર્ડ ખાતરી', name: 'પૂરું નામ', forgotPassword: 'પાસવર્ડ ભૂલી ગયા?', noAccount: 'ખાતું નથી?', hasAccount: 'પહેલેથી ખાતું છે?', signUp: 'સાઇન અપ', signIn: 'સાઇન ઇન', loginSuccess: 'લૉગિન સફળ!', registerSuccess: 'નોંધણી સફળ!', invalidCredentials: 'ખોટી માહિતી', welcomeBack: 'પાછા આવો!', createAccount: 'ખાતું બનાવો', getStarted: 'તમારી ફિટનેસ યાત્રા શરૂ કરો' },
  home: { greeting: 'નમસ્તે', todaySummary: 'આજનો સારાંશ', calories: 'કેલરી', protein: 'પ્રોટીન', carbs: 'કાર્બ્સ', fat: 'ચરબી', steps: 'પગલાં', stepsToday: 'આજના પગલાં', caloriesBurned: 'બળેલી કેલરી', goal: 'લક્ષ્ય', myNutrition: 'મારું પોષણ', myWorkout: 'મારો વ્યાયામ', progressTracking: 'પ્રગતિ ટ્રેકિંગ', yogaWellness: 'યોગ અને સુખાકારી', viewPlan: 'ભોજન યોજના જુઓ', trackWorkout: 'વ્યાયામ ટ્રેક કરો', trackProgress: 'શારીરિક પ્રગતિ ટ્રેક કરો', mindBody: 'મન અને શરીર', mealTracking: 'ભોજન ટ્રેકિંગ', haveYouTaken: 'તમે તમારું', meal: 'ભોજન લીધું?', mealTaken: 'ભોજન લીધું', mealNotTaken: 'તમે ટ્રેક પર નથી', markAsTaken: 'લીધું તરીકે ચિહ્નિત', workout: 'વ્યાયામ', workoutTime: 'ચાલો વ્યાયામ કરીએ!', workoutComplete: 'વ્યાયામ પૂરો કર્યો?', workoutDone: 'શાબાશ!', workoutCount: 'વ્યાયામ ગણતરી', logout: 'લૉગ આઉટ', logoutConfirm: 'ખરેખર લૉગ આઉટ કરવું છે?', replacedWith: 'થી બદલ્યું', didYouEatElse: 'બીજું કંઈ ખાધું?', whatDidYouEat: 'બદલે શું ખાધું?', enterFoodName: 'ખોરાકનું નામ દાખલ કરો', stepGoal: 'પગલાં લક્ષ્ય', congratsSteps: 'અભિનંદન! આજનું પગલાં લક્ષ્ય પૂર્ણ!', viewStepHistory: 'પગલાં ઇતિહાસ જુઓ', km: 'કિમી' },
  profile: { title: 'પ્રોફાઇલ', personalInfo: 'અંગત માહિતી', healthMetrics: 'સ્વાસ્થ્ય માપદંડ', goals: 'લક્ષ્યો', firstName: 'પ્રથમ નામ', lastName: 'અટક', age: 'ઉંમર', gender: 'લિંગ', male: 'પુરુષ', female: 'સ્ત્રી', other: 'અન્ય', selectGender: 'લિંગ પસંદ કરો', phone: 'ફોન', language: 'ભાષા', region: 'પ્રદેશ', selectRegion: 'પ્રદેશ પસંદ કરો', northIndia: 'ઉત્તર ભારત', southIndia: 'દક્ષિણ ભારત', eastIndia: 'પૂર્વ ભારત', westIndia: 'પશ્ચિમ ભારત', savePersonal: 'અંગત માહિતી સાચવો', height: 'ઊંચાઈ (સેમી)', currentWeight: 'હાલનું વજન (કિગ્રા)', targetWeight: 'લક્ષ્ય વજન (કિગ્રા)', activityLevel: 'પ્રવૃત્તિ સ્તર', sedentary: 'બેઠાડુ', light: 'હળવું', moderate: 'મધ્યમ', active: 'સક્રિય', veryActive: 'ખૂબ સક્રિય', healthConditions: 'સ્વાસ્થ્ય સ્થિતિઓ', addHealthCondition: 'સ્વાસ્થ્ય સ્થિતિ ઉમેરો', dietaryPreferences: 'ખોરાક પસંદગીઓ', vegetarian: 'શાકાહારી', nonVegetarian: 'માંસાહારી', vegan: 'વિગન', eggetarian: 'ઇંડા ખોરાક', saveHealth: 'સ્વાસ્થ્ય માહિતી સાચવો', selectGoals: 'તમારા લક્ષ્યો શું છે?', weightLoss: 'વજન ઘટાડવું', muscleGain: 'સ્નાયુ વધારવા', stayFit: 'ફિટ રહો', flexibility: 'લચીલાપણું', endurance: 'સહનશક્તિ', saveGoals: 'લક્ષ્યો સાચવો', profileSaved: 'પ્રોફાઇલ સાચવાયું!', healthSaved: 'સ્વાસ્થ્ય માહિતી સાચવાયી!', goalsSaved: 'લક્ષ્યો સાચવાયા!' },
  nutrition: { title: 'મારી પોષણ યોજના', generatePlan: 'યોજના બનાવો', newPlan: 'નવી યોજના', activePlan: 'સક્રિય યોજના', noPlan: 'પોષણ યોજના નથી', createFirst: 'પ્રથમ પોષણ યોજના બનાવો', totalCalories: 'કુલ કેલરી', mealPlan: 'ભોજન યોજના', breakfast: 'નાસ્તો', lunch: 'બપોરનું ભોજન', dinner: 'રાતનું ભોજન', snack: 'નાસ્તો', mealTotal: 'ભોજન કુલ', foodItems: 'ખોરાક વસ્તુઓ', quantity: 'જથ્થો', calories: 'કેલ', protein: 'પ્રોટીન', carbs: 'કાર્બ્સ', fat: 'ચરબી', fiber: 'ફાઇબર', preparationTips: 'તૈયારી ટિપ્સ', startPlan: 'યોજના શરૂ કરો', assignPlan: 'યોજના સોંપો', planAssigned: 'યોજના સોંપાઈ!', region: 'પ્રદેશ', dietType: 'આહાર પ્રકાર', foodPreferences: 'ખોરાક પસંદગીઓ', basedOnDiet: 'તમારા', diet: 'ખોરાક પર', customMeals: 'કસ્ટમ ભોજન', includePreWorkout: 'વ્યાયામ પહેલાં ભોજન', includePostWorkout: 'વ્યાયામ પછી ભોજન', wheyProtein: 'વ્હે પ્રોટીન લઈ શકો', supplements: 'સપ્લિમેન્ટ્સ', cookingOil: 'રસોઈ તેલ', preferHomemade: 'ઘરેલુ પસંદ', allergies: 'એલર્જી', dislikedFoods: 'નાપસંદ ખોરાક', newPlanTomorrow: 'નવી યોજના આવતીકાલથી', oldPlanActive: 'વર્તમાન યોજના મધ્યરાત્રિ સુધી' },
  workout: { title: 'મારો વ્યાયામ', setupTitle: 'વ્યાયામ સેટઅપ', generatePlan: 'વ્યાયામ યોજના બનાવો', exerciseDays: 'વ્યાયામ દિવસો', exerciseType: 'વ્યાયામ પ્રકાર', gym: 'જિમ', running: 'દોડ', yoga: 'યોગ', outdoor: 'બહાર', swimming: 'તરવું', workoutTime: 'વ્યાયામ સમય', duration: 'સમયગાળો (મિનિટ)', yourGoal: 'તમારું લક્ષ્ય', muscleBuilding: 'સ્નાયુ નિર્માણ', slimming: 'સ્લિમિંગ', slimmingMuscle: 'સ્લિમિંગ + સ્નાયુ', assignWorkout: 'વ્યાયામ સોંપો', weeklyOverview: 'સાપ્તાહિક ઝાંખી', setsReps: 'સેટ્સ & રેપ્સ', cardio: 'કાર્ડિઓ', estimatedCalories: 'અંદાજિત કેલરી બર્ન', noWorkout: 'વ્યાયામ યોજના નથી', createFirst: 'પ્રથમ વ્યાયામ યોજના', motivationalQuote: 'પ્રેરણાત્મક અવતરણ', workoutComplete: 'વ્યાયામ પૂર્ણ', greatJob: 'શાબાશ! ચાલુ રાખો!' },
  progress: { title: 'પ્રગતિ ટ્રેકિંગ', logWeight: 'વજન નોંધો', logMeasurements: 'માપ નોંધો', setGoal: 'લક્ષ્ય સેટ કરો', weightTrend: 'વજન ટ્રેન્ડ', bodyMeasurements: 'શારીરિક માપ', goals: 'લક્ષ્યો', weight: 'વજન (કિગ્રા)', bmi: 'બીએમઆઈ', bodyFat: 'શરીર ચરબી %', chest: 'છાતી (સેમી)', waist: 'કમર (સેમી)', hips: 'નિતંબ (સેમી)', arms: 'હાથ (સેમી)', thighs: 'સાથળ (સેમી)', neck: 'ગળું (સેમી)', goalType: 'લક્ષ્ય પ્રકાર', targetValue: 'લક્ષ્ય મૂલ્ય', currentValue: 'હાલનું મૂલ્ય', targetDate: 'લક્ષ્ય તારીખ', summary: 'સારાંશ', streak: 'શ્રેણી', days: 'દિવસો', weightChange: 'વજન ફેરફાર', notes: 'નોંધ', weightLogged: 'વજન નોંધાયું!', measurementsLogged: 'માપ નોંધાયા!', goalSet: 'લક્ષ્ય સેટ થયું!' },
  wellness: { title: 'યોગ અને સુખાકારી', dailyTip: 'દૈનિક સુખાકારી ટિપ', dayStreak: 'દિવસ શ્રેણી', sessions: 'સત્રો', minutes: 'મિનિટ', activePlan: 'સક્રિય યોજના', createPlan: 'સુખાકારી યોજના બનાવો', createPlanDesc: 'વ્યક્તિગત યોગ, ધ્યાન અને શ્વાસ યોજના', planSetup: 'યોજના સેટઅપ', type: 'પ્રકાર', yoga: 'યોગ', meditation: 'ધ્યાન', mixed: 'મિશ્ર', level: 'સ્તર', beginner: 'શરૂઆત', intermediate: 'મધ્યમ', advanced: 'અદ્યતન', duration: 'સમયગાળો', weeks: 'અઠવાડિયા', sessionsPerWeek: 'સત્રો/અઠવાડિયું', generatePlan: 'યોજના બનાવો', generatedPlan: 'બનાવેલી યોજના', assignPlan: 'આ યોજના સોંપો', yogaPoses: 'યોગ મુદ્રાઓ', meditationSessions: 'ધ્યાન', breathingExercises: 'શ્વાસ વ્યાયામ', markDone: 'પૂર્ણ ચિહ્નિત', alreadyDone: 'પહેલેથી પૂર્ણ', alreadyDoneMsg: 'આ સત્ર પહેલેથી પૂર્ણ!', sessionCompleted: 'સત્ર પૂર્ણ!', wellDone: 'ખૂબ સરસ!', benefits: 'ફાયદા', instructions: 'સૂચનાઓ', newPlan: 'નવી યોજના', currentPlanMidnight: 'હાલની યોજના મધ્યરાત્રિ સુધી.', calTotal: 'કેલ કુલ', min: 'મિનિ', cal: 'કેલ' },
  days: { monday: 'સોમવાર', tuesday: 'મંગળવાર', wednesday: 'બુધવાર', thursday: 'ગુરુવાર', friday: 'શુક્રવાર', saturday: 'શનિવાર', sunday: 'રવિવાર', mon: 'સોમ', tue: 'મંગ', wed: 'બુધ', thu: 'ગુરુ', fri: 'શુક્ર', sat: 'શનિ', sun: 'રવિ', today: 'આજે' },
  steps: { weekSummary: 'સાપ્તાહિક સારાંશ', totalSteps: 'કુલ પગલાં', dailyBreakdown: 'દૈનિક વિગત', stepsToday: 'આજના પગલાં', caloriesBurned: 'કેલરી', distance: 'અંતર', goalProgress: 'લક્ષ્ય', noStepData: 'પગલાં ડેટા નથી' },
};

