// Marathi (मराठी)
export default {
  common: { save: 'जतन करा', cancel: 'रद्द करा', delete: 'हटवा', edit: 'संपादित करा', back: '← मागे', loading: 'लोड होत आहे...', error: 'त्रुटी', success: 'यशस्वी', confirm: 'पुष्टी करा', yes: 'होय', no: 'नाही', ok: 'ठीक आहे', retry: 'पुन्हा प्रयत्न करा', done: 'झाले', next: 'पुढे', previous: 'मागील', submit: 'सबमिट करा', search: 'शोधा', noData: 'डेटा उपलब्ध नाही', comingSoon: 'लवकरच येत आहे' },
  auth: { login: 'लॉगिन', register: 'नोंदणी', email: 'ईमेल', password: 'पासवर्ड', confirmPassword: 'पासवर्ड पुष्टी करा', name: 'पूर्ण नाव', forgotPassword: 'पासवर्ड विसरलात?', noAccount: 'खाते नाही?', hasAccount: 'आधीच खाते आहे?', signUp: 'साइन अप', signIn: 'साइन इन', loginSuccess: 'लॉगिन यशस्वी!', registerSuccess: 'नोंदणी यशस्वी!', invalidCredentials: 'चुकीचे क्रेडेन्शियल', welcomeBack: 'पुन्हा स्वागत!', createAccount: 'खाते तयार करा', getStarted: 'तुमचा फिटनेस प्रवास सुरू करा' },
  home: { greeting: 'नमस्कार', todaySummary: 'आजचा सारांश', calories: 'कॅलरीज', protein: 'प्रथिने', carbs: 'कार्ब्स', fat: 'चरबी', steps: 'पावले', stepsToday: 'आजची पावले', caloriesBurned: 'जळलेल्या कॅलरीज', goal: 'ध्येय', myNutrition: 'माझे पोषण', myWorkout: 'माझा व्यायाम', progressTracking: 'प्रगती ट्रॅकिंग', yogaWellness: 'योग आणि कल्याण', viewPlan: 'जेवणाची योजना पहा', trackWorkout: 'व्यायाम ट्रॅक करा', trackProgress: 'शारीरिक प्रगती ट्रॅक करा', mindBody: 'मन आणि शरीर कल्याण', mealTracking: 'जेवण ट्रॅकिंग', haveYouTaken: 'तुम्ही तुमचे', meal: 'जेवण घेतले का', mealTaken: 'जेवण घेतले', mealNotTaken: 'तुम्ही ट्रॅकवर नाही', markAsTaken: 'घेतले म्हणून चिन्हांकित करा', workout: 'व्यायाम', workoutTime: 'चला व्यायाम करूया!', workoutComplete: 'व्यायाम पूर्ण केला?', workoutDone: 'छान!', workoutCount: 'व्यायाम गणना', logout: 'लॉग आउट', logoutConfirm: 'खरोखर लॉग आउट करायचे?', replacedWith: 'यापासून बदलले', didYouEatElse: 'दुसरे काही खाल्ले?', whatDidYouEat: 'त्याऐवजी काय खाल्ले?', enterFoodName: 'अन्नाचे नाव टाका', stepGoal: 'पावलांचे ध्येय', congratsSteps: 'अभिनंदन! आजचे पावलांचे ध्येय पूर्ण झाले!', viewStepHistory: 'पावलांचा इतिहास पहा', km: 'किमी' },
  profile: { title: 'प्रोफाइल', personalInfo: 'वैयक्तिक माहिती', healthMetrics: 'आरोग्य मापदंड', goals: 'ध्येये', firstName: 'पहिले नाव', lastName: 'आडनाव', age: 'वय', gender: 'लिंग', male: 'पुरुष', female: 'स्त्री', other: 'इतर', selectGender: 'लिंग निवडा', phone: 'फोन', language: 'भाषा', region: 'प्रदेश', selectRegion: 'प्रदेश निवडा', northIndia: 'उत्तर भारत', southIndia: 'दक्षिण भारत', eastIndia: 'पूर्व भारत', westIndia: 'पश्चिम भारत', savePersonal: 'वैयक्तिक माहिती जतन करा', height: 'उंची (सेमी)', currentWeight: 'सध्याचे वजन (किग्रॅ)', targetWeight: 'लक्ष्य वजन (किग्रॅ)', activityLevel: 'क्रियाकलाप पातळी', sedentary: 'निष्क्रिय', light: 'हलका', moderate: 'मध्यम', active: 'सक्रिय', veryActive: 'अतिसक्रिय', healthConditions: 'आरोग्य स्थिती', addHealthCondition: 'आरोग्य स्थिती जोडा', dietaryPreferences: 'आहार प्राधान्ये', vegetarian: 'शाकाहारी', nonVegetarian: 'मांसाहारी', vegan: 'वीगन', eggetarian: 'अंडाहारी', saveHealth: 'आरोग्य माहिती जतन करा', selectGoals: 'तुमची ध्येये काय आहेत?', weightLoss: 'वजन कमी करणे', muscleGain: 'स्नायू वाढवणे', stayFit: 'तंदुरुस्त राहा', flexibility: 'लवचिकता', endurance: 'सहनशीलता', saveGoals: 'ध्येये जतन करा', profileSaved: 'प्रोफाइल जतन झाले!', healthSaved: 'आरोग्य माहिती जतन झाली!', goalsSaved: 'ध्येये जतन झाली!' },
  nutrition: { title: 'माझी पोषण योजना', generatePlan: 'योजना तयार करा', newPlan: 'नवीन योजना', activePlan: 'सक्रिय योजना', noPlan: 'पोषण योजना नाही', createFirst: 'पहिली पोषण योजना तयार करा', totalCalories: 'एकूण कॅलरीज', mealPlan: 'जेवण योजना', breakfast: 'नाश्ता', lunch: 'दुपारचे जेवण', dinner: 'रात्रीचे जेवण', snack: 'नाश्ता', mealTotal: 'जेवण एकूण', foodItems: 'अन्न पदार्थ', quantity: 'प्रमाण', calories: 'कॅल', protein: 'प्रथिने', carbs: 'कार्ब्स', fat: 'चरबी', fiber: 'फायबर', preparationTips: 'तयारी सूचना', startPlan: 'योजना सुरू करा', assignPlan: 'योजना नियुक्त करा', planAssigned: 'योजना नियुक्त झाली!', region: 'प्रदेश', dietType: 'आहार प्रकार', foodPreferences: 'अन्न प्राधान्ये निवडा', basedOnDiet: 'तुमच्या', diet: 'आहारावर आधारित', customMeals: 'कस्टम जेवण', includePreWorkout: 'व्यायामपूर्व जेवण', includePostWorkout: 'व्यायामोत्तर जेवण', wheyProtein: 'व्हे प्रोटीन घेऊ शकतात', supplements: 'सप्लिमेंट्स', cookingOil: 'स्वयंपाक तेल', preferHomemade: 'घरी बनवलेले पसंत', allergies: 'ऍलर्जी', dislikedFoods: 'नापसंत अन्न', newPlanTomorrow: 'नवीन योजना उद्यापासून', oldPlanActive: 'सध्याची योजना मध्यरात्रीपर्यंत' },
  workout: { title: 'माझा व्यायाम', setupTitle: 'व्यायाम सेटअप', generatePlan: 'व्यायाम योजना तयार करा', exerciseDays: 'व्यायामाचे दिवस', exerciseType: 'व्यायामाचा प्रकार', gym: 'जिम', running: 'धावणे', yoga: 'योग', outdoor: 'बाहेरचा', swimming: 'पोहणे', workoutTime: 'व्यायामाची वेळ', duration: 'कालावधी (मिनिटे)', yourGoal: 'तुमचे ध्येय', muscleBuilding: 'स्नायू बांधणी', slimming: 'स्लिमिंग', slimmingMuscle: 'स्लिमिंग + स्नायू', assignWorkout: 'व्यायाम नियुक्त करा', weeklyOverview: 'साप्ताहिक आढावा', setsReps: 'सेट्स आणि रेप्स', cardio: 'कार्डिओ', estimatedCalories: 'अंदाजे कॅलरी बर्न', noWorkout: 'व्यायाम योजना नाही', createFirst: 'पहिली व्यायाम योजना तयार करा', motivationalQuote: 'प्रेरणादायी वचन', workoutComplete: 'व्यायाम पूर्ण', greatJob: 'छान! असेच चालू ठेवा!' },
  progress: { title: 'प्रगती ट्रॅकिंग', logWeight: 'वजन नोंदवा', logMeasurements: 'मापे नोंदवा', setGoal: 'ध्येय सेट करा', weightTrend: 'वजन ट्रेंड', bodyMeasurements: 'शारीरिक मापे', goals: 'ध्येये', weight: 'वजन (किग्रॅ)', bmi: 'बीएमआय', bodyFat: 'शरीर चरबी %', chest: 'छाती (सेमी)', waist: 'कंबर (सेमी)', hips: 'नितंब (सेमी)', arms: 'हात (सेमी)', thighs: 'मांडी (सेमी)', neck: 'मान (सेमी)', goalType: 'ध्येय प्रकार', targetValue: 'लक्ष्य मूल्य', currentValue: 'सध्याचे मूल्य', targetDate: 'लक्ष्य तारीख', summary: 'सारांश', streak: 'मालिका', days: 'दिवस', weightChange: 'वजन बदल', notes: 'टिपा', weightLogged: 'वजन नोंदले!', measurementsLogged: 'मापे नोंदली!', goalSet: 'ध्येय सेट झाले!' },
  wellness: { title: 'योग आणि कल्याण', dailyTip: 'दैनिक कल्याण सूचना', dayStreak: 'दिवसांची मालिका', sessions: 'सत्रे', minutes: 'मिनिटे', activePlan: 'सक्रिय योजना', createPlan: 'कल्याण योजना तयार करा', createPlanDesc: 'वैयक्तिक योग, ध्यान आणि श्वास योजना', planSetup: 'योजना सेटअप', type: 'प्रकार', yoga: 'योग', meditation: 'ध्यान', mixed: 'मिश्र', level: 'पातळी', beginner: 'नवशिक्या', intermediate: 'मध्यम', advanced: 'प्रगत', duration: 'कालावधी', weeks: 'आठवडे', sessionsPerWeek: 'सत्रे/आठवडा', generatePlan: 'योजना तयार करा', generatedPlan: 'तयार योजना', assignPlan: 'ही योजना नियुक्त करा', yogaPoses: 'योग आसने', meditationSessions: 'ध्यान', breathingExercises: 'श्वास व्यायाम', markDone: 'पूर्ण चिन्हांकित करा', alreadyDone: 'आधीच पूर्ण', alreadyDoneMsg: 'हे सत्र आधीच पूर्ण!', sessionCompleted: 'सत्र पूर्ण!', wellDone: 'शाबास!', benefits: 'फायदे', instructions: 'सूचना', newPlan: 'नवीन योजना', currentPlanMidnight: 'सध्याची योजना मध्यरात्रीपर्यंत.', calTotal: 'कॅल एकूण', min: 'मिनि', cal: 'कॅल' },
  days: { monday: 'सोमवार', tuesday: 'मंगळवार', wednesday: 'बुधवार', thursday: 'गुरुवार', friday: 'शुक्रवार', saturday: 'शनिवार', sunday: 'रविवार', mon: 'सोम', tue: 'मंगळ', wed: 'बुध', thu: 'गुरु', fri: 'शुक्र', sat: 'शनि', sun: 'रवि', today: 'आज' },
  steps: { weekSummary: 'साप्ताहिक सारांश', totalSteps: 'एकूण पावले', dailyBreakdown: 'दैनिक तपशील', stepsToday: 'आजची पावले', caloriesBurned: 'कॅलरीज', distance: 'अंतर', goalProgress: 'ध्येय', noStepData: 'पावलांचा डेटा नाही' },
};

