// Odia (ଓଡ଼ିଆ) - Core translations with fallback to English for missing keys
export default {
  common: { save: 'ସଂରକ୍ଷଣ', cancel: 'ବାତିଲ', delete: 'ବିଲୋପ', edit: 'ସମ୍ପାଦନା', back: '← ପଛକୁ', loading: 'ଲୋଡ ହେଉଛି...', error: 'ତ୍ରୁଟି', success: 'ସଫଳ', confirm: 'ନିଶ୍ଚିତ', yes: 'ହଁ', no: 'ନା', ok: 'ଠିକ ଅଛି', retry: 'ପୁନଃ ଚେଷ୍ଟା', done: 'ହୋଇଗଲା', next: 'ପରବର୍ତ୍ତୀ', previous: 'ପୂର୍ବ', submit: 'ଦାଖଲ', search: 'ସନ୍ଧାନ', noData: 'କୌଣସି ତଥ୍ୟ ନାହିଁ', comingSoon: 'ଶୀଘ୍ର ଆସୁଛି' },
  auth: { login: 'ଲଗଇନ', register: 'ପଞ୍ଜୀକରଣ', email: 'ଇମେଲ', password: 'ପାସୱାର୍ଡ', confirmPassword: 'ପାସୱାର୍ଡ ନିଶ୍ଚିତ', name: 'ସମ୍ପୂର୍ଣ୍ଣ ନାମ', forgotPassword: 'ପାସୱାର୍ଡ ଭୁଲିଗଲେ?', noAccount: 'ଖାତା ନାହିଁ?', hasAccount: 'ପୂର୍ବରୁ ଖାତା ଅଛି?', signUp: 'ସାଇନ ଅପ', signIn: 'ସାଇନ ଇନ', loginSuccess: 'ଲଗଇନ ସଫଳ!', registerSuccess: 'ପଞ୍ଜୀକରଣ ସଫଳ!', invalidCredentials: 'ଭୁଲ ତଥ୍ୟ', welcomeBack: 'ଫେରି ସ୍ୱାଗତ!', createAccount: 'ଖାତା ତିଆରି କରନ୍ତୁ', getStarted: 'ଆପଣଙ୍କ ଫିଟନେସ ଯାତ୍ରା ଆରମ୍ଭ କରନ୍ତୁ' },
  home: { greeting: 'ନମସ୍କାର', todaySummary: 'ଆଜିର ସାରାଂଶ', calories: 'କ୍ୟାଲୋରି', protein: 'ପ୍ରୋଟିନ', carbs: 'କାର୍ବସ', fat: 'ଚର୍ବି', steps: 'ପାଦ', stepsToday: 'ଆଜିର ପାଦ', caloriesBurned: 'ଜଳିଥିବା କ୍ୟାଲୋରି', goal: 'ଲକ୍ଷ୍ୟ', myNutrition: 'ମୋ ପୋଷଣ', myWorkout: 'ମୋ ବ୍ୟାୟାମ', progressTracking: 'ଅଗ୍ରଗତି ଟ୍ରାକିଂ', yogaWellness: 'ଯୋଗ ଓ ସୁସ୍ଥତା', viewPlan: 'ଖାଦ୍ୟ ଯୋଜନା ଦେଖନ୍ତୁ', trackWorkout: 'ବ୍ୟାୟାମ ଟ୍ରାକ', trackProgress: 'ଶାରୀରିକ ଅଗ୍ରଗତି ଟ୍ରାକ', mindBody: 'ମନ ଓ ଶରୀର', mealTracking: 'ଖାଦ୍ୟ ଟ୍ରାକିଂ', haveYouTaken: 'ଆପଣ ଆପଣଙ୍କ', meal: 'ଖାଦ୍ୟ ଖାଇଲେ?', mealTaken: 'ଖାଦ୍ୟ ଖାଇଲେ', mealNotTaken: 'ଆପଣ ଟ୍ରାକରେ ନାହାନ୍ତି', markAsTaken: 'ଖାଇଥିବା ଚିହ୍ନିତ', workout: 'ବ୍ୟାୟାମ', workoutTime: 'ଚାଲନ୍ତୁ ବ୍ୟାୟାମ କରିବା!', workoutComplete: 'ବ୍ୟାୟାମ ସମ୍ପୂର୍ଣ୍ଣ?', workoutDone: 'ବହୁତ ଭଲ!', workoutCount: 'ବ୍ୟାୟାମ ଗଣନା', logout: 'ଲଗ ଆଉଟ', logoutConfirm: 'ସତରେ ଲଗ ଆଉଟ ହେବେ?', replacedWith: 'ବଦଳରେ', didYouEatElse: 'ଅନ୍ୟ କିଛି ଖାଇଲେ?', whatDidYouEat: 'ବଦଳରେ କ\'ଣ ଖାଇଲେ?', enterFoodName: 'ଖାଦ୍ୟ ନାମ ଲେଖନ୍ତୁ', stepGoal: 'ପାଦ ଲକ୍ଷ୍ୟ', congratsSteps: 'ଅଭିନନ୍ଦନ! ଆଜିର ପାଦ ଲକ୍ଷ୍ୟ ସମ୍ପୂର୍ଣ୍ଣ!', viewStepHistory: 'ପାଦ ଇତିହାସ', km: 'କିମି' },
  profile: { title: 'ପ୍ରୋଫାଇଲ', personalInfo: 'ବ୍ୟକ୍ତିଗତ ତଥ୍ୟ', healthMetrics: 'ସ୍ୱାସ୍ଥ୍ୟ ମାପ', goals: 'ଲକ୍ଷ୍ୟ', firstName: 'ପ୍ରଥମ ନାମ', lastName: 'ଶେଷ ନାମ', age: 'ବୟସ', gender: 'ଲିଙ୍ଗ', male: 'ପୁରୁଷ', female: 'ମହିଳା', other: 'ଅନ୍ୟ', selectGender: 'ଲିଙ୍ଗ ବାଛନ୍ତୁ', phone: 'ଫୋନ', language: 'ଭାଷା', region: 'ଅଞ୍ଚଳ', selectRegion: 'ଅଞ୍ଚଳ ବାଛନ୍ତୁ', northIndia: 'ଉତ୍ତର ଭାରତ', southIndia: 'ଦକ୍ଷିଣ ଭାରତ', eastIndia: 'ପୂର୍ବ ଭାରତ', westIndia: 'ପଶ୍ଚିମ ଭାରତ', savePersonal: 'ବ୍ୟକ୍ତିଗତ ତଥ୍ୟ ସଂରକ୍ଷଣ', height: 'ଉଚ୍ଚତା (ସେମି)', currentWeight: 'ବର୍ତ୍ତମାନ ଓଜନ (କେଜି)', targetWeight: 'ଲକ୍ଷ୍ୟ ଓଜନ (କେଜି)', activityLevel: 'କାର୍ଯ୍ୟ ସ୍ତର', sedentary: 'ନିଷ୍କ୍ରିୟ', light: 'ହାଲୁକା', moderate: 'ମଧ୍ୟମ', active: 'ସକ୍ରିୟ', veryActive: 'ଅତ୍ୟନ୍ତ ସକ୍ରିୟ', healthConditions: 'ସ୍ୱାସ୍ଥ୍ୟ ସ୍ଥିତି', addHealthCondition: 'ସ୍ୱାସ୍ଥ୍ୟ ସ୍ଥିତି ଯୋଡ଼ନ୍ତୁ', dietaryPreferences: 'ଖାଦ୍ୟ ପସନ୍ଦ', vegetarian: 'ନିରାମିଷ', nonVegetarian: 'ଆମିଷ', vegan: 'ଭିଗାନ', eggetarian: 'ଅଣ୍ଡା ଖାଦ୍ୟ', saveHealth: 'ସ୍ୱାସ୍ଥ୍ୟ ତଥ୍ୟ ସଂରକ୍ଷଣ', selectGoals: 'ଆପଣଙ୍କ ଲକ୍ଷ୍ୟ?', weightLoss: 'ଓଜନ ହ୍ରାସ', muscleGain: 'ମାଂସପେଶୀ ବୃଦ୍ଧି', stayFit: 'ସୁସ୍ଥ ରୁହନ୍ତୁ', flexibility: 'ନମନୀୟତା', endurance: 'ସହନଶୀଳତା', saveGoals: 'ଲକ୍ଷ୍ୟ ସଂରକ୍ଷଣ', profileSaved: 'ପ୍ରୋଫାଇଲ ସଂରକ୍ଷିତ!', healthSaved: 'ସ୍ୱାସ୍ଥ୍ୟ ତଥ୍ୟ ସଂରକ୍ଷିତ!', goalsSaved: 'ଲକ୍ଷ୍ୟ ସଂରକ୍ଷିତ!' },
  nutrition: { title: 'ମୋ ପୋଷଣ ଯୋଜନା', generatePlan: 'ଯୋଜନା ତିଆରି', newPlan: 'ନୂଆ ଯୋଜନା', activePlan: 'ସକ୍ରିୟ ଯୋଜନା', noPlan: 'ପୋଷଣ ଯୋଜନା ନାହିଁ', createFirst: 'ପ୍ରଥମ ପୋଷଣ ଯୋଜନା ତିଆରି', totalCalories: 'ସମ୍ପୂର୍ଣ୍ଣ କ୍ୟାଲୋରି', mealPlan: 'ଖାଦ୍ୟ ଯୋଜନା', breakfast: 'ସକାଳ ଜଳଖିଆ', lunch: 'ମଧ୍ୟାହ୍ନ ଭୋଜନ', dinner: 'ରାତ୍ରି ଭୋଜନ', snack: 'ଜଳଖିଆ', mealTotal: 'ଖାଦ୍ୟ ସମୁଦାୟ', foodItems: 'ଖାଦ୍ୟ ସାମଗ୍ରୀ', quantity: 'ପରିମାଣ', calories: 'କ୍ୟାଲ', protein: 'ପ୍ରୋଟିନ', carbs: 'କାର୍ବସ', fat: 'ଚର୍ବି', fiber: 'ଫାଇବର', preparationTips: 'ପ୍ରସ୍ତୁତି ସୂଚନା', startPlan: 'ଯୋଜନା ଆରମ୍ଭ', assignPlan: 'ଯୋଜନା ନିଯୁକ୍ତ', planAssigned: 'ଯୋଜନା ନିଯୁକ୍ତ!', region: 'ଅଞ୍ଚଳ', dietType: 'ଖାଦ୍ୟ ପ୍ରକାର', foodPreferences: 'ଖାଦ୍ୟ ପସନ୍ଦ', basedOnDiet: 'ଆପଣଙ୍କ', diet: 'ଖାଦ୍ୟ ଆଧାରରେ', customMeals: 'କଷ୍ଟମ ଖାଦ୍ୟ', includePreWorkout: 'ବ୍ୟାୟାମ ପୂର୍ବ ଖାଦ୍ୟ', includePostWorkout: 'ବ୍ୟାୟାମ ପର ଖାଦ୍ୟ', wheyProtein: 'ୱେ ପ୍ରୋଟିନ ନେଇପାରିବେ', supplements: 'ସପ୍ଲିମେଣ୍ଟ', cookingOil: 'ରାନ୍ଧିବା ତେଲ', preferHomemade: 'ଘରେ ତିଆରି ପସନ୍ଦ', allergies: 'ଆଲର୍ଜି', dislikedFoods: 'ଅପସନ୍ଦ ଖାଦ୍ୟ', newPlanTomorrow: 'ନୂଆ ଯୋଜନା ଆସନ୍ତାକାଲିଠୁ', oldPlanActive: 'ବର୍ତ୍ତମାନ ଯୋଜନା ମଧ୍ୟରାତ୍ରି ପର୍ଯ୍ୟନ୍ତ' },
  workout: { title: 'ମୋ ବ୍ୟାୟାମ', setupTitle: 'ବ୍ୟାୟାମ ସେଟଅପ', generatePlan: 'ବ୍ୟାୟାମ ଯୋଜନା ତିଆରି', exerciseDays: 'ବ୍ୟାୟାମ ଦିନ', exerciseType: 'ବ୍ୟାୟାମ ପ୍ରକାର', gym: 'ଜିମ', running: 'ଦୌଡ଼', yoga: 'ଯୋଗ', outdoor: 'ବାହାରେ', swimming: 'ପହଁରା', workoutTime: 'ବ୍ୟାୟାମ ସମୟ', duration: 'ସମୟ (ମିନିଟ)', yourGoal: 'ଆପଣଙ୍କ ଲକ୍ଷ୍ୟ', muscleBuilding: 'ମାଂସପେଶୀ ନିର୍ମାଣ', slimming: 'ସ୍ଲିମିଂ', slimmingMuscle: 'ସ୍ଲିମିଂ + ମାଂସପେଶୀ', assignWorkout: 'ବ୍ୟାୟାମ ନିଯୁକ୍ତ', weeklyOverview: 'ସାପ୍ତାହିକ ସମୀକ୍ଷା', setsReps: 'ସେଟ ଓ ରେପ', cardio: 'କାର୍ଡିଓ', estimatedCalories: 'ଆନୁମାନିକ କ୍ୟାଲୋରି', noWorkout: 'ବ୍ୟାୟାମ ଯୋଜନା ନାହିଁ', createFirst: 'ପ୍ରଥମ ବ୍ୟାୟାମ ଯୋଜନା', motivationalQuote: 'ପ୍ରେରଣାଦାୟକ ଉକ୍ତି', workoutComplete: 'ବ୍ୟାୟାମ ସମ୍ପୂର୍ଣ୍ଣ', greatJob: 'ବହୁତ ଭଲ! ଚାଲୁ ରଖନ୍ତୁ!' },
  progress: { title: 'ଅଗ୍ରଗତି ଟ୍ରାକିଂ', logWeight: 'ଓଜନ ଲିପିବଦ୍ଧ', logMeasurements: 'ମାପ ଲିପିବଦ୍ଧ', setGoal: 'ଲକ୍ଷ୍ୟ ସ୍ଥିର', weightTrend: 'ଓଜନ ପ୍ରବୃତ୍ତି', bodyMeasurements: 'ଶାରୀରିକ ମାପ', goals: 'ଲକ୍ଷ୍ୟ', weight: 'ଓଜନ (କେଜି)', bmi: 'ବିଏମଆଇ', bodyFat: 'ଶରୀର ଚର୍ବି %', chest: 'ଛାତି (ସେମି)', waist: 'କମ୍ବଳ (ସେମି)', hips: 'ନିତମ୍ବ (ସେମି)', arms: 'ବାହୁ (ସେମି)', thighs: 'ଊରୁ (ସେମି)', neck: 'ବେକ (ସେମି)', goalType: 'ଲକ୍ଷ୍ୟ ପ୍ରକାର', targetValue: 'ଲକ୍ଷ୍ୟ ମୂଲ୍ୟ', currentValue: 'ବର୍ତ୍ତମାନ ମୂଲ୍ୟ', targetDate: 'ଲକ୍ଷ୍ୟ ତାରିଖ', summary: 'ସାରାଂଶ', streak: 'ଧାରା', days: 'ଦିନ', weightChange: 'ଓଜନ ପରିବର୍ତ୍ତନ', notes: 'ଟିପ୍ପଣୀ', weightLogged: 'ଓଜନ ଲିପିବଦ୍ଧ!', measurementsLogged: 'ମାପ ଲିପିବଦ୍ଧ!', goalSet: 'ଲକ୍ଷ୍ୟ ସ୍ଥିର!' },
  wellness: { title: 'ଯୋଗ ଓ ସୁସ୍ଥତା', dailyTip: 'ଦୈନିକ ସୁସ୍ଥତା ସୂଚନା', dayStreak: 'ଦିନ ଧାରା', sessions: 'ସେଶନ', minutes: 'ମିନିଟ', activePlan: 'ସକ୍ରିୟ ଯୋଜନା', createPlan: 'ସୁସ୍ଥତା ଯୋଜନା ତିଆରି', createPlanDesc: 'ବ୍ୟକ୍ତିଗତ ଯୋଗ, ଧ୍ୟାନ ଓ ଶ୍ୱାସ ଯୋଜନା', planSetup: 'ଯୋଜନା ସେଟଅପ', type: 'ପ୍ରକାର', yoga: 'ଯୋଗ', meditation: 'ଧ୍ୟାନ', mixed: 'ମିଶ୍ରିତ', level: 'ସ୍ତର', beginner: 'ଆରମ୍ଭ', intermediate: 'ମଧ୍ୟ', advanced: 'ଉନ୍ନତ', duration: 'ସମୟ', weeks: 'ସପ୍ତାହ', sessionsPerWeek: 'ସେଶନ/ସପ୍ତାହ', generatePlan: 'ଯୋଜନା ତିଆରି', generatedPlan: 'ତିଆରି ଯୋଜନା', assignPlan: 'ଏହି ଯୋଜନା ନିଯୁକ୍ତ', yogaPoses: 'ଯୋଗ ଆସନ', meditationSessions: 'ଧ୍ୟାନ', breathingExercises: 'ଶ୍ୱାସ ବ୍ୟାୟାମ', markDone: 'ସମ୍ପୂର୍ଣ୍ଣ ଚିହ୍ନିତ', alreadyDone: 'ଆଗରୁ ସମ୍ପୂର୍ଣ୍ଣ', alreadyDoneMsg: 'ଏହି ସେଶନ ଆଜି ଆଗରୁ ସମ୍ପୂର୍ଣ୍ଣ!', sessionCompleted: 'ସେଶନ ସମ୍ପୂର୍ଣ୍ଣ!', wellDone: 'ବହୁତ ଭଲ!', benefits: 'ଲାଭ', instructions: 'ନିର୍ଦ୍ଦେଶ', newPlan: 'ନୂଆ ଯୋଜନା', currentPlanMidnight: 'ବର୍ତ୍ତମାନ ଯୋଜନା ମଧ୍ୟରାତ୍ରି ପର୍ଯ୍ୟନ୍ତ.', calTotal: 'କ୍ୟାଲ ମୋଟ', min: 'ମିନି', cal: 'କ୍ୟାଲ' },
  days: { monday: 'ସୋମବାର', tuesday: 'ମଙ୍ଗଳବାର', wednesday: 'ବୁଧବାର', thursday: 'ଗୁରୁବାର', friday: 'ଶୁକ୍ରବାର', saturday: 'ଶନିବାର', sunday: 'ରବିବାର', mon: 'ସୋମ', tue: 'ମଙ୍ଗ', wed: 'ବୁଧ', thu: 'ଗୁରୁ', fri: 'ଶୁକ୍ର', sat: 'ଶନି', sun: 'ରବି', today: 'ଆଜି' },
  steps: { weekSummary: 'ସାପ୍ତାହିକ ସାରାଂଶ', totalSteps: 'ସମ୍ପୂର୍ଣ୍ଣ ପାଦ', dailyBreakdown: 'ଦୈନିକ ବିବରଣୀ', stepsToday: 'ଆଜିର ପାଦ', caloriesBurned: 'କ୍ୟାଲୋରି', distance: 'ଦୂରତା', goalProgress: 'ଲକ୍ଷ୍ୟ', noStepData: 'ପାଦ ତଥ୍ୟ ନାହିଁ' },
};

