// Punjabi (ਪੰਜਾਬੀ)
export default {
  common: { save: 'ਸੇਵ ਕਰੋ', cancel: 'ਰੱਦ ਕਰੋ', delete: 'ਮਿਟਾਓ', edit: 'ਸੋਧੋ', back: '← ਪਿੱਛੇ', loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...', error: 'ਗਲਤੀ', success: 'ਸਫ਼ਲ', confirm: 'ਪੁਸ਼ਟੀ ਕਰੋ', yes: 'ਹਾਂ', no: 'ਨਹੀਂ', ok: 'ਠੀਕ ਹੈ', retry: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼', done: 'ਹੋ ਗਿਆ', next: 'ਅਗਲਾ', previous: 'ਪਿਛਲਾ', submit: 'ਜਮ੍ਹਾ ਕਰੋ', search: 'ਖੋਜੋ', noData: 'ਕੋਈ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ', comingSoon: 'ਜਲਦ ਆ ਰਿਹਾ ਹੈ' },
  auth: { login: 'ਲੌਗਇਨ', register: 'ਰਜਿਸਟਰ', email: 'ਈਮੇਲ', password: 'ਪਾਸਵਰਡ', confirmPassword: 'ਪਾਸਵਰਡ ਪੁਸ਼ਟੀ', name: 'ਪੂਰਾ ਨਾਮ', forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?', noAccount: 'ਖਾਤਾ ਨਹੀਂ?', hasAccount: 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?', signUp: 'ਸਾਈਨ ਅੱਪ', signIn: 'ਸਾਈਨ ਇਨ', loginSuccess: 'ਲੌਗਇਨ ਸਫ਼ਲ!', registerSuccess: 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਫ਼ਲ!', invalidCredentials: 'ਗ਼ਲਤ ਜਾਣਕਾਰੀ', welcomeBack: 'ਵਾਪਸ ਸਵਾਗਤ ਹੈ!', createAccount: 'ਖਾਤਾ ਬਣਾਓ', getStarted: 'ਆਪਣੀ ਫਿਟਨੈੱਸ ਯਾਤਰਾ ਸ਼ੁਰੂ ਕਰੋ' },
  home: { greeting: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ', todaySummary: 'ਅੱਜ ਦਾ ਸਾਰ', calories: 'ਕੈਲੋਰੀ', protein: 'ਪ੍ਰੋਟੀਨ', carbs: 'ਕਾਰਬਸ', fat: 'ਚਰਬੀ', steps: 'ਕਦਮ', stepsToday: 'ਅੱਜ ਦੇ ਕਦਮ', caloriesBurned: 'ਸੜੀਆਂ ਕੈਲੋਰੀ', goal: 'ਟੀਚਾ', myNutrition: 'ਮੇਰਾ ਪੋਸ਼ਣ', myWorkout: 'ਮੇਰੀ ਕਸਰਤ', progressTracking: 'ਤਰੱਕੀ ਟ੍ਰੈਕਿੰਗ', yogaWellness: 'ਯੋਗ ਅਤੇ ਤੰਦਰੁਸਤੀ', viewPlan: 'ਖੁਰਾਕ ਯੋਜਨਾ ਦੇਖੋ', trackWorkout: 'ਕਸਰਤ ਟ੍ਰੈਕ ਕਰੋ', trackProgress: 'ਸਰੀਰਕ ਤਰੱਕੀ ਟ੍ਰੈਕ', mindBody: 'ਮਨ ਅਤੇ ਸਰੀਰ', mealTracking: 'ਖੁਰਾਕ ਟ੍ਰੈਕਿੰਗ', haveYouTaken: 'ਕੀ ਤੁਸੀਂ ਆਪਣਾ', meal: 'ਖਾਣਾ ਖਾਧਾ', mealTaken: 'ਖਾਣਾ ਖਾਧਾ', mealNotTaken: 'ਤੁਸੀਂ ਟ੍ਰੈਕ ਤੇ ਨਹੀਂ', markAsTaken: 'ਖਾਧਾ ਚਿੰਨ੍ਹਿਤ ਕਰੋ', workout: 'ਕਸਰਤ', workoutTime: 'ਚੱਲੋ ਕਸਰਤ ਕਰੀਏ!', workoutComplete: 'ਕਸਰਤ ਪੂਰੀ ਕੀਤੀ?', workoutDone: 'ਸ਼ਾਬਾਸ਼!', workoutCount: 'ਕਸਰਤ ਗਿਣਤੀ', logout: 'ਲੌਗ ਆਊਟ', logoutConfirm: 'ਕੀ ਤੁਸੀਂ ਸੱਚਮੁੱਚ ਲੌਗ ਆਊਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?', replacedWith: 'ਨਾਲ ਬਦਲਿਆ', didYouEatElse: 'ਕੁਝ ਹੋਰ ਖਾਧਾ?', whatDidYouEat: 'ਬਦਲੇ ਵਿੱਚ ਕੀ ਖਾਧਾ?', enterFoodName: 'ਖਾਣੇ ਦਾ ਨਾਮ ਦਿਓ', stepGoal: 'ਕਦਮ ਟੀਚਾ', congratsSteps: 'ਵਧਾਈਆਂ! ਅੱਜ ਦਾ ਕਦਮ ਟੀਚਾ ਪੂਰਾ!', viewStepHistory: 'ਕਦਮ ਇਤਿਹਾਸ ਦੇਖੋ', km: 'ਕਿਮੀ' },
  profile: { title: 'ਪ੍ਰੋਫ਼ਾਈਲ', personalInfo: 'ਨਿੱਜੀ ਜਾਣਕਾਰੀ', healthMetrics: 'ਸਿਹਤ ਮਾਪ', goals: 'ਟੀਚੇ', firstName: 'ਪਹਿਲਾ ਨਾਮ', lastName: 'ਆਖ਼ਰੀ ਨਾਮ', age: 'ਉਮਰ', gender: 'ਲਿੰਗ', male: 'ਮਰਦ', female: 'ਔਰਤ', other: 'ਹੋਰ', selectGender: 'ਲਿੰਗ ਚੁਣੋ', phone: 'ਫ਼ੋਨ', language: 'ਭਾਸ਼ਾ', region: 'ਖੇਤਰ', selectRegion: 'ਖੇਤਰ ਚੁਣੋ', northIndia: 'ਉੱਤਰੀ ਭਾਰਤ', southIndia: 'ਦੱਖਣੀ ਭਾਰਤ', eastIndia: 'ਪੂਰਬੀ ਭਾਰਤ', westIndia: 'ਪੱਛਮੀ ਭਾਰਤ', savePersonal: 'ਨਿੱਜੀ ਜਾਣਕਾਰੀ ਸੇਵ', height: 'ਕੱਦ (ਸੈਮੀ)', currentWeight: 'ਮੌਜੂਦਾ ਭਾਰ (ਕਿਲੋ)', targetWeight: 'ਟੀਚਾ ਭਾਰ (ਕਿਲੋ)', activityLevel: 'ਗਤੀਵਿਧੀ ਪੱਧਰ', sedentary: 'ਬੈਠਾ', light: 'ਹਲਕਾ', moderate: 'ਦਰਮਿਆਨਾ', active: 'ਸਰਗਰਮ', veryActive: 'ਬਹੁਤ ਸਰਗਰਮ', healthConditions: 'ਸਿਹਤ ਸਥਿਤੀਆਂ', addHealthCondition: 'ਸਿਹਤ ਸਥਿਤੀ ਜੋੜੋ', dietaryPreferences: 'ਖੁਰਾਕ ਪਸੰਦ', vegetarian: 'ਸ਼ਾਕਾਹਾਰੀ', nonVegetarian: 'ਮਾਸਾਹਾਰੀ', vegan: 'ਵੀਗਨ', eggetarian: 'ਅੰਡਾ ਖੁਰਾਕ', saveHealth: 'ਸਿਹਤ ਜਾਣਕਾਰੀ ਸੇਵ', selectGoals: 'ਤੁਹਾਡੇ ਟੀਚੇ ਕੀ ਹਨ?', weightLoss: 'ਭਾਰ ਘਟਾਉਣਾ', muscleGain: 'ਮਾਸਪੇਸ਼ੀ ਵਧਾਉਣਾ', stayFit: 'ਫਿੱਟ ਰਹੋ', flexibility: 'ਲਚਕੀਲਾਪਣ', endurance: 'ਸਹਿਣਸ਼ਕਤੀ', saveGoals: 'ਟੀਚੇ ਸੇਵ', profileSaved: 'ਪ੍ਰੋਫ਼ਾਈਲ ਸੇਵ ਹੋ ਗਈ!', healthSaved: 'ਸਿਹਤ ਜਾਣਕਾਰੀ ਸੇਵ ਹੋ ਗਈ!', goalsSaved: 'ਟੀਚੇ ਸੇਵ ਹੋ ਗਏ!' },
  nutrition: { title: 'ਮੇਰੀ ਪੋਸ਼ਣ ਯੋਜਨਾ', generatePlan: 'ਯੋਜਨਾ ਬਣਾਓ', newPlan: 'ਨਵੀਂ ਯੋਜਨਾ', activePlan: 'ਸਰਗਰਮ ਯੋਜਨਾ', noPlan: 'ਕੋਈ ਪੋਸ਼ਣ ਯੋਜਨਾ ਨਹੀਂ', createFirst: 'ਪਹਿਲੀ ਪੋਸ਼ਣ ਯੋਜਨਾ ਬਣਾਓ', totalCalories: 'ਕੁੱਲ ਕੈਲੋਰੀ', mealPlan: 'ਖੁਰਾਕ ਯੋਜਨਾ', breakfast: 'ਨਾਸ਼ਤਾ', lunch: 'ਦੁਪਹਿਰ ਦਾ ਖਾਣਾ', dinner: 'ਰਾਤ ਦਾ ਖਾਣਾ', snack: 'ਸਨੈਕ', mealTotal: 'ਖੁਰਾਕ ਕੁੱਲ', foodItems: 'ਖਾਣ ਦੀਆਂ ਚੀਜ਼ਾਂ', quantity: 'ਮਾਤਰਾ', calories: 'ਕੈਲ', protein: 'ਪ੍ਰੋਟੀਨ', carbs: 'ਕਾਰਬਸ', fat: 'ਚਰਬੀ', fiber: 'ਫ਼ਾਈਬਰ', preparationTips: 'ਤਿਆਰੀ ਸੁਝਾਅ', startPlan: 'ਯੋਜਨਾ ਸ਼ੁਰੂ', assignPlan: 'ਯੋਜਨਾ ਅਸਾਈਨ', planAssigned: 'ਯੋਜਨਾ ਅਸਾਈਨ ਹੋ ਗਈ!', region: 'ਖੇਤਰ', dietType: 'ਖੁਰਾਕ ਕਿਸਮ', foodPreferences: 'ਖੁਰਾਕ ਪਸੰਦ', basedOnDiet: 'ਤੁਹਾਡੀ', diet: 'ਖੁਰਾਕ ਮੁਤਾਬਕ', customMeals: 'ਕਸਟਮ ਖੁਰਾਕ', includePreWorkout: 'ਕਸਰਤ ਤੋਂ ਪਹਿਲਾਂ ਖੁਰਾਕ', includePostWorkout: 'ਕਸਰਤ ਤੋਂ ਬਾਅਦ ਖੁਰਾਕ', wheyProtein: 'ਵੇ ਪ੍ਰੋਟੀਨ ਲੈ ਸਕਦੇ', supplements: 'ਸਪਲੀਮੈਂਟ', cookingOil: 'ਖਾਣਾ ਪਕਾਉਣ ਦਾ ਤੇਲ', preferHomemade: 'ਘਰੇਲੂ ਪਸੰਦ', allergies: 'ਐਲਰਜੀ', dislikedFoods: 'ਨਾਪਸੰਦ ਖਾਣੇ', newPlanTomorrow: 'ਨਵੀਂ ਯੋਜਨਾ ਕੱਲ੍ਹ ਤੋਂ', oldPlanActive: 'ਮੌਜੂਦਾ ਯੋਜਨਾ ਅੱਧੀ ਰਾਤ ਤੱਕ' },
  workout: { title: 'ਮੇਰੀ ਕਸਰਤ', setupTitle: 'ਕਸਰਤ ਸੈੱਟਅੱਪ', generatePlan: 'ਕਸਰਤ ਯੋਜਨਾ ਬਣਾਓ', exerciseDays: 'ਕਸਰਤ ਦੇ ਦਿਨ', exerciseType: 'ਕਸਰਤ ਦੀ ਕਿਸਮ', gym: 'ਜਿਮ', running: 'ਦੌੜ', yoga: 'ਯੋਗ', outdoor: 'ਬਾਹਰੀ', swimming: 'ਤੈਰਾਕੀ', workoutTime: 'ਕਸਰਤ ਦਾ ਸਮਾਂ', duration: 'ਸਮਾਂ (ਮਿੰਟ)', yourGoal: 'ਤੁਹਾਡਾ ਟੀਚਾ', muscleBuilding: 'ਮਾਸਪੇਸ਼ੀ ਬਣਾਉਣਾ', slimming: 'ਸਲਿਮਿੰਗ', slimmingMuscle: 'ਸਲਿਮਿੰਗ + ਮਾਸਪੇਸ਼ੀ', assignWorkout: 'ਕਸਰਤ ਅਸਾਈਨ', weeklyOverview: 'ਹਫ਼ਤਾਵਾਰੀ ਸੰਖੇਪ', setsReps: 'ਸੈੱਟ ਅਤੇ ਰੈੱਪ', cardio: 'ਕਾਰਡੀਓ', estimatedCalories: 'ਅੰਦਾਜ਼ਨ ਕੈਲੋਰੀ ਬਰਨ', noWorkout: 'ਕੋਈ ਕਸਰਤ ਯੋਜਨਾ ਨਹੀਂ', createFirst: 'ਪਹਿਲੀ ਕਸਰਤ ਯੋਜਨਾ', motivationalQuote: 'ਪ੍ਰੇਰਨਾਦਾਇਕ ਸੁਵਿਚਾਰ', workoutComplete: 'ਕਸਰਤ ਪੂਰੀ', greatJob: 'ਸ਼ਾਬਾਸ਼! ਜਾਰੀ ਰੱਖੋ!' },
  progress: { title: 'ਤਰੱਕੀ ਟ੍ਰੈਕਿੰਗ', logWeight: 'ਭਾਰ ਦਰਜ ਕਰੋ', logMeasurements: 'ਮਾਪ ਦਰਜ ਕਰੋ', setGoal: 'ਟੀਚਾ ਸੈੱਟ ਕਰੋ', weightTrend: 'ਭਾਰ ਰੁਝਾਨ', bodyMeasurements: 'ਸਰੀਰਕ ਮਾਪ', goals: 'ਟੀਚੇ', weight: 'ਭਾਰ (ਕਿਲੋ)', bmi: 'ਬੀਐਮਆਈ', bodyFat: 'ਸਰੀਰ ਚਰਬੀ %', chest: 'ਛਾਤੀ (ਸੈਮੀ)', waist: 'ਕਮਰ (ਸੈਮੀ)', hips: 'ਨਿੱਤ (ਸੈਮੀ)', arms: 'ਬਾਹਾਂ (ਸੈਮੀ)', thighs: 'ਪੱਟ (ਸੈਮੀ)', neck: 'ਗਰਦਨ (ਸੈਮੀ)', goalType: 'ਟੀਚਾ ਕਿਸਮ', targetValue: 'ਟੀਚਾ ਮੁੱਲ', currentValue: 'ਮੌਜੂਦਾ ਮੁੱਲ', targetDate: 'ਟੀਚਾ ਤਾਰੀਖ਼', summary: 'ਸੰਖੇਪ', streak: 'ਲੜੀ', days: 'ਦਿਨ', weightChange: 'ਭਾਰ ਬਦਲਾਅ', notes: 'ਨੋਟ', weightLogged: 'ਭਾਰ ਦਰਜ ਹੋ ਗਿਆ!', measurementsLogged: 'ਮਾਪ ਦਰਜ ਹੋ ਗਏ!', goalSet: 'ਟੀਚਾ ਸੈੱਟ ਹੋ ਗਿਆ!' },
  wellness: { title: 'ਯੋਗ ਅਤੇ ਤੰਦਰੁਸਤੀ', dailyTip: 'ਰੋਜ਼ਾਨਾ ਤੰਦਰੁਸਤੀ ਸੁਝਾਅ', dayStreak: 'ਦਿਨ ਲੜੀ', sessions: 'ਸੈਸ਼ਨ', minutes: 'ਮਿੰਟ', activePlan: 'ਸਰਗਰਮ ਯੋਜਨਾ', createPlan: 'ਤੰਦਰੁਸਤੀ ਯੋਜਨਾ ਬਣਾਓ', createPlanDesc: 'ਨਿੱਜੀ ਯੋਗ, ਧਿਆਨ ਅਤੇ ਸਾਹ ਯੋਜਨਾ', planSetup: 'ਯੋਜਨਾ ਸੈੱਟਅੱਪ', type: 'ਕਿਸਮ', yoga: 'ਯੋਗ', meditation: 'ਧਿਆਨ', mixed: 'ਮਿਲਵਾਂ', level: 'ਪੱਧਰ', beginner: 'ਸ਼ੁਰੂਆਤੀ', intermediate: 'ਦਰਮਿਆਨਾ', advanced: 'ਐਡਵਾਂਸਡ', duration: 'ਸਮਾਂ', weeks: 'ਹਫ਼ਤੇ', sessionsPerWeek: 'ਸੈਸ਼ਨ/ਹਫ਼ਤਾ', generatePlan: 'ਯੋਜਨਾ ਬਣਾਓ', generatedPlan: 'ਬਣਾਈ ਯੋਜਨਾ', assignPlan: 'ਇਹ ਯੋਜਨਾ ਅਸਾਈਨ', yogaPoses: 'ਯੋਗ ਆਸਣ', meditationSessions: 'ਧਿਆਨ', breathingExercises: 'ਸਾਹ ਕਸਰਤ', markDone: 'ਪੂਰਾ ਚਿੰਨ੍ਹਿਤ', alreadyDone: 'ਪਹਿਲਾਂ ਹੀ ਪੂਰਾ', alreadyDoneMsg: 'ਅੱਜ ਇਹ ਸੈਸ਼ਨ ਪਹਿਲਾਂ ਹੀ ਪੂਰਾ!', sessionCompleted: 'ਸੈਸ਼ਨ ਪੂਰਾ!', wellDone: 'ਬਹੁਤ ਵਧੀਆ!', benefits: 'ਫ਼ਾਇਦੇ', instructions: 'ਹਦਾਇਤਾਂ', newPlan: 'ਨਵੀਂ ਯੋਜਨਾ', currentPlanMidnight: 'ਮੌਜੂਦਾ ਯੋਜਨਾ ਅੱਧੀ ਰਾਤ ਤੱਕ.', calTotal: 'ਕੈਲ ਕੁੱਲ', min: 'ਮਿੰਟ', cal: 'ਕੈਲ' },
  days: { monday: 'ਸੋਮਵਾਰ', tuesday: 'ਮੰਗਲਵਾਰ', wednesday: 'ਬੁੱਧਵਾਰ', thursday: 'ਵੀਰਵਾਰ', friday: 'ਸ਼ੁੱਕਰਵਾਰ', saturday: 'ਸ਼ਨਿੱਚਰਵਾਰ', sunday: 'ਐਤਵਾਰ', mon: 'ਸੋਮ', tue: 'ਮੰਗ', wed: 'ਬੁੱਧ', thu: 'ਵੀਰ', fri: 'ਸ਼ੁੱਕ', sat: 'ਸ਼ਨਿ', sun: 'ਐਤ', today: 'ਅੱਜ' },
  steps: { weekSummary: 'ਹਫ਼ਤਾਵਾਰੀ ਸੰਖੇਪ', totalSteps: 'ਕੁੱਲ ਕਦਮ', dailyBreakdown: 'ਰੋਜ਼ਾਨਾ ਵੇਰਵਾ', stepsToday: 'ਅੱਜ ਦੇ ਕਦਮ', caloriesBurned: 'ਕੈਲੋਰੀ', distance: 'ਦੂਰੀ', goalProgress: 'ਟੀਚਾ', noStepData: 'ਕਦਮ ਡਾਟਾ ਨਹੀਂ' },
};

