export default {
  common: {
    save: 'சேமி', cancel: 'ரத்து செய்', delete: 'நீக்கு', edit: 'திருத்து', back: '← பின்', loading: 'ஏற்றுகிறது...', error: 'பிழை', success: 'வெற்றி', confirm: 'உறுதிசெய்', yes: 'ஆம்', no: 'இல்லை', ok: 'சரி', retry: 'மீண்டும் முயற்சி', done: 'முடிந்தது', next: 'அடுத்து', previous: 'முந்தைய', submit: 'சமர்ப்பி', search: 'தேடு', noData: 'தரவு இல்லை', comingSoon: 'விரைவில் வருகிறது',
  },
  auth: {
    login: 'உள்நுழை', register: 'பதிவு', email: 'மின்னஞ்சல்', password: 'கடவுச்சொல்', confirmPassword: 'கடவுச்சொல் உறுதி', name: 'முழுப் பெயர்', forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?', noAccount: 'கணக்கு இல்லையா?', hasAccount: 'ஏற்கனவே கணக்கு உள்ளதா?', signUp: 'பதிவு செய்', signIn: 'உள்நுழை', loginSuccess: 'உள்நுழைவு வெற்றி!', registerSuccess: 'பதிவு வெற்றி!', invalidCredentials: 'தவறான சான்றுகள்', welcomeBack: 'மீண்டும் வரவேற்கிறோம்!', createAccount: 'கணக்கை உருவாக்கு', getStarted: 'உங்கள் ஆரோக்கிய பயணத்தைத் தொடங்குங்கள்',
  },
  home: {
    greeting: 'வணக்கம்', todaySummary: 'இன்றைய சுருக்கம்', calories: 'கலோரிகள்', protein: 'புரதம்', carbs: 'மாவுச்சத்து', fat: 'கொழுப்பு', steps: 'அடிகள்', stepsToday: 'இன்றைய அடிகள்', caloriesBurned: 'எரிக்கப்பட்ட கலோரிகள்', goal: 'இலக்கு', myNutrition: 'என் ஊட்டச்சத்து', myWorkout: 'என் பயிற்சி', progressTracking: 'முன்னேற்ற கண்காணிப்பு', yogaWellness: 'யோகா & நலம்', viewPlan: 'உணவுத் திட்டத்தைப் பார்', trackWorkout: 'பயிற்சி கண்காணி', trackProgress: 'உடல் முன்னேற்றம் கண்காணி', mindBody: 'மனம் & உடல் நலம்', mealTracking: 'உணவு கண்காணிப்பு', haveYouTaken: 'நீங்கள் உங்கள்', meal: 'உணவை எடுத்தீர்களா', mealTaken: 'உணவு எடுக்கப்பட்டது', mealNotTaken: 'நீங்கள் சரியான பாதையில் இல்லை', markAsTaken: 'எடுத்ததாகக் குறி', workout: 'பயிற்சி', workoutTime: 'பயிற்சிக்குச் செல்வோம்!', workoutComplete: 'பயிற்சி முடித்தீர்களா?', workoutDone: 'நல்ல வேலை!', workoutCount: 'பயிற்சி எண்ணிக்கை', logout: 'வெளியேறு', logoutConfirm: 'நிச்சயமாக வெளியேற விரும்புகிறீர்களா?', replacedWith: 'இதனால் மாற்றப்பட்டது', didYouEatElse: 'வேறு ஏதாவது சாப்பிட்டீர்களா?', whatDidYouEat: 'அதற்கு பதிலாக என்ன சாப்பிட்டீர்கள்?', enterFoodName: 'உணவின் பெயரை உள்ளிடுங்கள்', stepGoal: 'அடி இலக்கு', congratsSteps: 'வாழ்த்துக்கள்! இன்றைய அடி இலக்கை நிறைவு செய்தீர்கள்!', viewStepHistory: 'அடி வரலாற்றைப் பார்', km: 'கிமீ',
  },
  profile: {
    title: 'சுயவிவரம்', personalInfo: 'தனிப்பட்ட தகவல்', healthMetrics: 'ஆரோக்கிய அளவீடுகள்', goals: 'இலக்குகள்', firstName: 'முதல் பெயர்', lastName: 'கடைசி பெயர்', age: 'வயது', gender: 'பாலினம்', male: 'ஆண்', female: 'பெண்', other: 'மற்றவை', selectGender: 'பாலினத்தைத் தேர்ந்தெடுக்கவும்', phone: 'தொலைபேசி', language: 'மொழி', region: 'பகுதி', selectRegion: 'உங்கள் பகுதியைத் தேர்ந்தெடுக்கவும்', northIndia: 'வட இந்தியா', southIndia: 'தென் இந்தியா', eastIndia: 'கிழக்கு இந்தியா', westIndia: 'மேற்கு இந்தியா', savePersonal: 'தனிப்பட்ட தகவல் சேமி', height: 'உயரம் (செமீ)', currentWeight: 'தற்போதைய எடை (கிகி)', targetWeight: 'இலக்கு எடை (கிகி)', activityLevel: 'செயல்பாட்டு நிலை', sedentary: 'உட்கார்ந்த (குறைந்த பயிற்சி)', light: 'இலகு (வாரம் 1-3 நாள்)', moderate: 'மிதமான (வாரம் 3-5 நாள்)', active: 'சுறுசுறுப்பான (வாரம் 6-7 நாள்)', veryActive: 'மிகவும் சுறுசுறுப்பான (தினசரி கடுமையான பயிற்சி)', healthConditions: 'உடல்நல நிலைகள்', addHealthCondition: 'உடல்நல நிலை சேர்', dietaryPreferences: 'உணவு விருப்பங்கள்', vegetarian: 'சைவம்', nonVegetarian: 'அசைவம்', vegan: 'வீகன்', eggetarian: 'முட்டை உணவு', saveHealth: 'ஆரோக்கிய தகவல் சேமி', selectGoals: 'உங்கள் இலக்குகள் என்ன?', weightLoss: 'எடை குறைப்பு', muscleGain: 'தசை வளர்ப்பு', stayFit: 'ஆரோக்கியமாக இரு', flexibility: 'நெகிழ்வுத்தன்மை', endurance: 'நீடித்த சக்தி', saveGoals: 'இலக்குகள் சேமி', profileSaved: 'சுயவிவரம் சேமிக்கப்பட்டது!', healthSaved: 'ஆரோக்கிய தகவல் சேமிக்கப்பட்டது!', goalsSaved: 'இலக்குகள் சேமிக்கப்பட்டன!',
  },
  nutrition: {
    title: 'என் ஊட்டச்சத்து திட்டம்', generatePlan: 'திட்டம் உருவாக்கு', newPlan: 'புதிய திட்டம்', activePlan: 'செயலில் உள்ள திட்டம்', noPlan: 'ஊட்டச்சத்து திட்டம் இல்லை', createFirst: 'முதல் ஊட்டச்சத்து திட்டத்தை உருவாக்குங்கள்', totalCalories: 'மொத்த கலோரிகள்', mealPlan: 'உணவுத் திட்டம்', breakfast: 'காலை உணவு', lunch: 'மதிய உணவு', dinner: 'இரவு உணவு', snack: 'சிற்றுண்டி', mealTotal: 'உணவு மொத்தம்', foodItems: 'உணவு பொருட்கள்', quantity: 'அளவு', calories: 'கலோ', protein: 'புரதம்', carbs: 'மாவுச்சத்து', fat: 'கொழுப்பு', fiber: 'நார்ச்சத்து', preparationTips: 'தயாரிப்பு குறிப்புகள்', startPlan: 'திட்டம் தொடங்கு', assignPlan: 'திட்டம் ஒதுக்கு', planAssigned: 'திட்டம் ஒதுக்கப்பட்டது!', region: 'பகுதி', dietType: 'உணவு வகை', foodPreferences: 'உணவு விருப்பங்கள் தேர்வு', basedOnDiet: 'உங்கள்', diet: 'உணவின் அடிப்படையில்', customMeals: 'தனிப்பயன் உணவுகள்', includePreWorkout: 'பயிற்சிக்கு முன் உணவு', includePostWorkout: 'பயிற்சிக்குப் பின் உணவு', wheyProtein: 'வே புரதம் எடுக்கலாம்', supplements: 'சப்ளிமெண்ட்ஸ்', cookingOil: 'சமையல் எண்ணெய் விருப்பம்', preferHomemade: 'வீட்டில் தயாரிக்கப்பட்டது விரும்பு', allergies: 'ஒவ்வாமை', dislikedFoods: 'விரும்பாத உணவுகள்', newPlanTomorrow: 'புதிய திட்டம் நாளையிலிருந்து தொடங்கும்', oldPlanActive: 'நடப்பு திட்டம் நள்ளிரவு வரை செயலில் இருக்கும்',
  },
  workout: {
    title: 'என் பயிற்சி', setupTitle: 'பயிற்சி அமைப்பு', generatePlan: 'பயிற்சி திட்டம் உருவாக்கு', exerciseDays: 'பயிற்சி நாட்கள்', exerciseType: 'பயிற்சி வகை', gym: 'ஜிம்', running: 'ஓட்டம்', yoga: 'யோகா', outdoor: 'வெளிப்புறம்', swimming: 'நீச்சல்', workoutTime: 'பயிற்சி நேரம்', duration: 'கால அளவு (நிமிடம்)', yourGoal: 'உங்கள் இலக்கு', muscleBuilding: 'தசை வளர்ப்பு', slimming: 'மெலிதாக்கல்', slimmingMuscle: 'மெலிதாக்கல் + தசை', assignWorkout: 'பயிற்சி ஒதுக்கு', weeklyOverview: 'வாராந்திர கண்ணோட்டம்', setsReps: 'செட் & ரெப்ஸ்', cardio: 'கார்டியோ', estimatedCalories: 'மதிப்பிடப்பட்ட கலோரி எரிப்பு', noWorkout: 'பயிற்சி திட்டம் இல்லை', createFirst: 'முதல் பயிற்சி திட்டத்தை உருவாக்குங்கள்', motivationalQuote: 'ஊக்க மேற்கோள்', workoutComplete: 'பயிற்சி முடிந்தது', greatJob: 'நல்ல வேலை! தொடருங்கள்!',
  },
  progress: {
    title: 'முன்னேற்ற கண்காணிப்பு', logWeight: 'எடை பதிவு', logMeasurements: 'அளவீடு பதிவு', setGoal: 'இலக்கு அமை', weightTrend: 'எடை போக்கு', bodyMeasurements: 'உடல் அளவீடுகள்', goals: 'இலக்குகள்', weight: 'எடை (கிகி)', bmi: 'பிஎம்ஐ', bodyFat: 'உடல் கொழுப்பு %', chest: 'மார்பு (செமீ)', waist: 'இடுப்பு (செமீ)', hips: 'இடுப்பெலும்பு (செமீ)', arms: 'கைகள் (செமீ)', thighs: 'தொடைகள் (செமீ)', neck: 'கழுத்து (செமீ)', goalType: 'இலக்கு வகை', targetValue: 'இலக்கு மதிப்பு', currentValue: 'தற்போதைய மதிப்பு', targetDate: 'இலக்கு தேதி', summary: 'சுருக்கம்', streak: 'தொடர்ச்சி', days: 'நாட்கள்', weightChange: 'எடை மாற்றம்', notes: 'குறிப்புகள்', weightLogged: 'எடை பதிவு செய்யப்பட்டது!', measurementsLogged: 'அளவீடுகள் பதிவு செய்யப்பட்டன!', goalSet: 'இலக்கு அமைக்கப்பட்டது!',
  },
  wellness: {
    title: 'யோகா & நலம்', dailyTip: 'தினசரி நல குறிப்பு', dayStreak: 'தினசரி தொடர்', sessions: 'அமர்வுகள்', minutes: 'நிமிடங்கள்', activePlan: 'செயலில் உள்ள திட்டம்', createPlan: 'நல திட்டம் உருவாக்கு', createPlanDesc: 'தனிப்பயன் யோகா, தியானம் & சுவாசப் பயிற்சி திட்டம்', planSetup: 'திட்ட அமைப்பு', type: 'வகை', yoga: 'யோகா', meditation: 'தியானம்', mixed: 'கலப்பு', level: 'நிலை', beginner: 'ஆரம்பம்', intermediate: 'நடுத்தரம்', advanced: 'மேம்பட்டது', duration: 'கால அளவு', weeks: 'வாரங்கள்', sessionsPerWeek: 'அமர்வுகள்/வாரம்', generatePlan: 'திட்டம் உருவாக்கு', generatedPlan: 'உருவாக்கப்பட்ட திட்டம்', assignPlan: 'இந்த திட்டம் ஒதுக்கு', yogaPoses: 'யோகா நிலைகள்', meditationSessions: 'தியானம்', breathingExercises: 'சுவாசப் பயிற்சிகள்', markDone: 'முடிந்ததாகக் குறி', alreadyDone: 'ஏற்கனவே முடிந்தது', alreadyDoneMsg: 'இன்று இந்த அமர்வை ஏற்கனவே முடித்துவிட்டீர்கள்!', sessionCompleted: 'அமர்வு முடிந்தது!', wellDone: 'நன்றாக செய்தீர்கள்!', benefits: 'பலன்கள்', instructions: 'வழிமுறைகள்', newPlan: 'புதிய திட்டம்', currentPlanMidnight: 'நடப்பு திட்டம் நள்ளிரவு வரை, புதியது நாளை தொடங்கும்.', calTotal: 'கலோ மொத்தம்', min: 'நிமி', cal: 'கலோ',
  },
  days: { monday: 'திங்கள்', tuesday: 'செவ்வாய்', wednesday: 'புதன்', thursday: 'வியாழன்', friday: 'வெள்ளி', saturday: 'சனி', sunday: 'ஞாயிறு', mon: 'திங்', tue: 'செவ்', wed: 'புத', thu: 'வியா', fri: 'வெள்', sat: 'சனி', sun: 'ஞாயி', today: 'இன்று' },
  steps: { weekSummary: 'வார சுருக்கம்', totalSteps: 'மொத்த அடிகள்', dailyBreakdown: 'தினசரி விவரம்', stepsToday: 'இன்றைய அடிகள்', caloriesBurned: 'கலோரிகள்', distance: 'தூரம்', goalProgress: 'இலக்கு', noStepData: 'அடி தரவு இல்லை' },
};

